(ns com.fulcrologic.semantic-ui.icons)

(def _500px-icon "500px")
(def accessible-icon "accessible")
(def accusoft-icon "accusoft")
(def add-circle-icon "add circle")
(def add-icon "add")
(def add-square-icon "add square")
(def add-to-calendar-icon "add to calendar")
(def add-to-cart-icon "add to cart")
(def add-user-icon "add user")
(def address-book-icon "address book")
(def address-book-outline-icon "address book outline")
(def address-card-icon "address card")
(def address-card-outline-icon "address card outline")
(def adjust-icon "adjust")
(def adn-icon "adn")
(def adversal-icon "adversal")
(def affiliatetheme-icon "affiliatetheme")
(def alarm-icon "alarm")
(def alarm-mute-icon "alarm mute")
(def ald-icon "ald")
(def algolia-icon "algolia")
(def align-center-icon "align center")
(def align-justify-icon "align justify")
(def align-left-icon "align left")
(def align-right-icon "align right")
(def als-icon "als")
(def amazon-icon "amazon")
(def amazon-pay-icon "amazon pay")
(def ambulance-icon "ambulance")
(def american-sign-language-interpreting-icon "american sign language interpreting")
(def amilia-icon "amilia")
(def anchor-icon "anchor")
(def android-icon "android")
(def angellist-icon "angellist")
(def angle-double-down-icon "angle double down")
(def angle-double-left-icon "angle double left")
(def angle-double-right-icon "angle double right")
(def angle-double-up-icon "angle double up")
(def angle-down-icon "angle down")
(def angle-left-icon "angle left")
(def angle-right-icon "angle right")
(def angle-up-icon "angle up")
(def angrycreative-icon "angrycreative")
(def angular-icon "angular")
(def announcement-icon "announcement")
(def app-store-icon "app store")
(def app-store-ios-icon "app store ios")
(def apper-icon "apper")
(def apple-icon "apple")
(def apple-pay-icon "apple pay")
(def archive-icon "archive")
(def area-chart-icon "area chart")
(def area-graph-icon "area graph")
(def arrow-alternate-circle-down-icon "arrow alternate circle down")
(def arrow-alternate-circle-down-outline-icon "arrow alternate circle down outline")
(def arrow-alternate-circle-left-icon "arrow alternate circle left")
(def arrow-alternate-circle-left-outline-icon "arrow alternate circle left outline")
(def arrow-alternate-circle-right-icon "arrow alternate circle right")
(def arrow-alternate-circle-right-outline-icon "arrow alternate circle right outline")
(def arrow-alternate-circle-up-icon "arrow alternate circle up")
(def arrow-alternate-circle-up-outline-icon "arrow alternate circle up outline")
(def arrow-circle-down-icon "arrow circle down")
(def arrow-circle-left-icon "arrow circle left")
(def arrow-circle-right-icon "arrow circle right")
(def arrow-circle-up-icon "arrow circle up")
(def arrow-down-cart-icon "arrow down cart")
(def arrow-down-icon "arrow down")
(def arrow-left-icon "arrow left")
(def arrow-right-icon "arrow right")
(def arrow-up-icon "arrow up")
(def arrows-alternate-horizontal-icon "arrows alternate horizontal")
(def arrows-alternate-icon "arrows alternate")
(def arrows-alternate-vertical-icon "arrows alternate vertical")
(def asexual-icon "asexual")
(def asl-icon "asl")
(def asl-interpreting-icon "asl interpreting")
(def assistive-listening-devices-icon "assistive listening devices")
(def assistive-listening-systems-icon "assistive listening systems")
(def asterisk-icon "asterisk")
(def asymmetrik-icon "asymmetrik")
(def at-icon "at")
(def attach-icon "attach")
(def attention-icon "attention")
(def audible-icon "audible")
(def audio-description-icon "audio description")
(def autoprefixer-icon "autoprefixer")
(def avianex-icon "avianex")
(def aviato-icon "aviato")
(def aws-icon "aws")
(def backward-icon "backward")
(def balance-icon "balance")
(def balance-scale-icon "balance scale")
(def ban-icon "ban")
(def band-aid-icon "band aid")
(def bandcamp-icon "bandcamp")
(def bar-icon "bar")
(def barcode-icon "barcode")
(def bars-icon "bars")
(def baseball-ball-icon "baseball ball")
(def basketball-ball-icon "basketball ball")
(def bath-icon "bath")
(def bathtub-icon "bathtub")
(def battery-empty-icon "battery empty")
(def battery-four-icon "battery four")
(def battery-full-icon "battery full")
(def battery-half-icon "battery half")
(def battery-high-icon "battery high")
(def battery-low-icon "battery low")
(def battery-one-icon "battery one")
(def battery-quarter-icon "battery quarter")
(def battery-three-icon "battery three")
(def battery-three-quarters-icon "battery three quarters")
(def battery-two-icon "battery two")
(def battery-zero-icon "battery zero")
(def bed-icon "bed")
(def beer-icon "beer")
(def behance-icon "behance")
(def behance-square-icon "behance square")
(def bell-icon "bell")
(def bell-outline-icon "bell outline")
(def bell-slash-icon "bell slash")
(def bell-slash-outline-icon "bell slash outline")
(def bicycle-icon "bicycle")
(def bimobject-icon "bimobject")
(def binoculars-icon "binoculars")
(def birthday-cake-icon "birthday cake")
(def birthday-icon "birthday")
(def bitbucket-icon "bitbucket")
(def bitbucket-square-icon "bitbucket square")
(def bitcoin-icon "bitcoin")
(def bity-icon "bity")
(def black-tie-icon "black tie")
(def blackberry-icon "blackberry")
(def blind-icon "blind")
(def block-layout-icon "block layout")
(def blogger-b-icon "blogger b")
(def blogger-icon "blogger")
(def bluetooth-alternative-icon "bluetooth alternative")
(def bluetooth-b-icon "bluetooth b")
(def bluetooth-icon "bluetooth")
(def bold-icon "bold")
(def bolt-icon "bolt")
(def bomb-icon "bomb")
(def book-icon "book")
(def bookmark-icon "bookmark")
(def bookmark-outline-icon "bookmark outline")
(def bowling-ball-icon "bowling ball")
(def box-icon "box")
(def boxes-icon "boxes")
(def braille-icon "braille")
(def briefcase-icon "briefcase")
(def broken-chain-icon "broken chain")
(def browser-icon "browser")
(def btc-icon "btc")
(def bug-icon "bug")
(def building-icon "building")
(def building-outline-icon "building outline")
(def bullhorn-icon "bullhorn")
(def bullseye-icon "bullseye")
(def buromobelexperte-icon "buromobelexperte")
(def bus-icon "bus")
(def buysellads-icon "buysellads")
(def calculator-icon "calculator")
(def calendar-alternate-icon "calendar alternate")
(def calendar-alternate-outline-icon "calendar alternate outline")
(def calendar-check-icon "calendar check")
(def calendar-check-outline-icon "calendar check outline")
(def calendar-icon "calendar")
(def calendar-minus-icon "calendar minus")
(def calendar-minus-outline-icon "calendar minus outline")
(def calendar-outline-icon "calendar outline")
(def calendar-plus-icon "calendar plus")
(def calendar-plus-outline-icon "calendar plus outline")
(def calendar-times-icon "calendar times")
(def calendar-times-outline-icon "calendar times outline")
(def call-icon "call")
(def call-square-icon "call square")
(def camera-icon "camera")
(def camera-retro-icon "camera retro")
(def cancel-icon "cancel")
(def car-icon "car")
(def caret-down-icon "caret down")
(def caret-left-icon "caret left")
(def caret-right-icon "caret right")
(def caret-square-down-icon "caret square down")
(def caret-square-down-outline-icon "caret square down outline")
(def caret-square-left-icon "caret square left")
(def caret-square-left-outline-icon "caret square left outline")
(def caret-square-right-icon "caret square right")
(def caret-square-right-outline-icon "caret square right outline")
(def caret-square-up-icon "caret square up")
(def caret-square-up-outline-icon "caret square up outline")
(def caret-up-icon "caret up")
(def cart-arrow-down-icon "cart arrow down")
(def cart-icon "cart")
(def cart-plus-icon "cart plus")
(def cc-amazon-pay-icon "cc amazon pay")
(def cc-amex-icon "cc amex")
(def cc-apple-pay-icon "cc apple pay")
(def cc-diners-club-icon "cc diners club")
(def cc-discover-icon "cc discover")
(def cc-icon "cc")
(def cc-jcb-icon "cc jcb")
(def cc-mastercard-icon "cc mastercard")
(def cc-paypal-icon "cc paypal")
(def cc-stripe-icon "cc stripe")
(def cc-visa-icon "cc visa")
(def centercode-icon "centercode")
(def certificate-icon "certificate")
(def chain-icon "chain")
(def chart-area-icon "chart area")
(def chart-bar-icon "chart bar")
(def chart-bar-outline-icon "chart bar outline")
(def chart-line-icon "chart line")
(def chart-pie-icon "chart pie")
(def chat-icon "chat")
(def check-circle-icon "check circle")
(def check-circle-outline-icon "check circle outline")
(def check-icon "check")
(def check-square-icon "check square")
(def check-square-outline-icon "check square outline")
(def checked-calendar-icon "checked calendar")
(def checkmark-box-icon "checkmark box")
(def checkmark-icon "checkmark")
(def chess-bishop-icon "chess bishop")
(def chess-board-icon "chess board")
(def chess-icon "chess")
(def chess-king-icon "chess king")
(def chess-knight-icon "chess knight")
(def chess-pawn-icon "chess pawn")
(def chess-queen-icon "chess queen")
(def chess-rock-icon "chess rock")
(def chess-rook-icon "chess rook")
(def chevron-circle-down-icon "chevron circle down")
(def chevron-circle-left-icon "chevron circle left")
(def chevron-circle-right-icon "chevron circle right")
(def chevron-circle-up-icon "chevron circle up")
(def chevron-down-icon "chevron down")
(def chevron-left-icon "chevron left")
(def chevron-right-icon "chevron right")
(def chevron-up-icon "chevron up")
(def child-icon "child")
(def chrome-icon "chrome")
(def circle-icon "circle")
(def circle-notch-icon "circle notch")
(def circle-notched-icon "circle notched")
(def circle-outline-icon "circle outline")
(def circle-thin-icon "circle thin")
(def clipboard-check-icon "clipboard check")
(def clipboard-icon "clipboard")
(def clipboard-list-icon "clipboard list")
(def clipboard-outline-icon "clipboard outline")
(def clock-icon "clock")
(def clock-outline-icon "clock outline")
(def clone-icon "clone")
(def clone-outline-icon "clone outline")
(def close-icon "close")
(def closed-captioning-icon "closed captioning")
(def closed-captioning-outline-icon "closed captioning outline")
(def cloud-download-icon "cloud download")
(def cloud-icon "cloud")
(def cloud-upload-icon "cloud upload")
(def cloudscale-icon "cloudscale")
(def cloudsmith-icon "cloudsmith")
(def cloudversify-icon "cloudversify")
(def cny-icon "cny")
(def cocktail-icon "cocktail")
(def code-branch-icon "code branch")
(def code-icon "code")
(def codepen-icon "codepen")
(def codiepie-icon "codiepie")
(def coffee-icon "coffee")
(def cog-icon "cog")
(def cogs-icon "cogs")
(def columns-icon "columns")
(def comment-alternate-icon "comment alternate")
(def comment-alternate-outline-icon "comment alternate outline")
(def comment-icon "comment")
(def comment-outline-icon "comment outline")
(def commenting-icon "commenting")
(def comments-icon "comments")
(def comments-outline-icon "comments outline")
(def compass-icon "compass")
(def compass-outline-icon "compass outline")
(def compose-icon "compose")
(def compress-icon "compress")
(def computer-icon "computer")
(def configure-icon "configure")
(def connectdevelop-icon "connectdevelop")
(def contao-icon "contao")
(def content-icon "content")
(def conversation-icon "conversation")
(def copy-icon "copy")
(def copy-outline-icon "copy outline")
(def copyright-icon "copyright")
(def copyright-outline-icon "copyright outline")
(def cpanel-icon "cpanel")
(def creative-commons-icon "creative commons")
(def credit-card-alternative-icon "credit card alternative")
(def credit-card-icon "credit card")
(def credit-card-outline-icon "credit card outline")
(def crop-icon "crop")
(def crosshairs-icon "crosshairs")
(def css3-alternate-icon "css3 alternate")
(def css3-icon "css3")
(def cube-icon "cube")
(def cubes-icon "cubes")
(def currency-icon "currency")
(def cut-icon "cut")
(def cuttlefish-icon "cuttlefish")
(def d-and-d-icon "d and d")
(def dashboard-icon "dashboard")
(def dashcube-icon "dashcube")
(def database-icon "database")
(def deaf-icon "deaf")
(def deafness-icon "deafness")
(def delete-calendar-icon "delete calendar")
(def delete-icon "delete")
(def delicious-icon "delicious")
(def deploydog-icon "deploydog")
(def deskpro-icon "deskpro")
(def desktop-icon "desktop")
(def detective-icon "detective")
(def deviantart-icon "deviantart")
(def diamond-icon "diamond")
(def digg-icon "digg")
(def digital-ocean-icon "digital ocean")
(def discord-icon "discord")
(def discourse-icon "discourse")
(def discussions-icon "discussions")
(def disk-icon "disk")
(def dna-icon "dna")
(def dochub-icon "dochub")
(def docker-icon "docker")
(def doctor-icon "doctor")
(def dollar-icon "dollar")
(def dollar-sign-icon "dollar sign")
(def dolly-flatbed-icon "dolly flatbed")
(def dolly-icon "dolly")
(def dont-icon "dont")
(def dot-circle-icon "dot circle")
(def dot-circle-outline-icon "dot circle outline")
(def download-icon "download")
(def draft2digital-icon "draft2digital")
(def dribbble-icon "dribbble")
(def dribbble-square-icon "dribbble square")
(def drivers-license-icon "drivers license")
(def dropbox-icon "dropbox")
(def dropdown-icon "dropdown")
(def drupal-icon "drupal")
(def dyalog-icon "dyalog")
(def earlybirds-icon "earlybirds")
(def edge-icon "edge")
(def edit-icon "edit")
(def edit-outline-icon "edit outline")
(def eject-icon "eject")
(def elementor-icon "elementor")
(def ellipsis-horizontal-icon "ellipsis horizontal")
(def ellipsis-vertical-icon "ellipsis vertical")
(def ember-icon "ember")
(def emergency-icon "emergency")
(def empire-icon "empire")
(def envelope-icon "envelope")
(def envelope-open-icon "envelope open")
(def envelope-open-outline-icon "envelope open outline")
(def envelope-outline-icon "envelope outline")
(def envelope-square-icon "envelope square")
(def envira-gallery-icon "envira gallery")
(def envira-icon "envira")
(def erase-icon "erase")
(def eraser-icon "eraser")
(def erlang-icon "erlang")
(def ethereum-icon "ethereum")
(def etsy-icon "etsy")
(def eur-icon "eur")
(def euro-icon "euro")
(def euro-sign-icon "euro sign")
(def exchange-icon "exchange")
(def exclamation-circle-icon "exclamation circle")
(def exclamation-icon "exclamation")
(def exclamation-triangle-icon "exclamation triangle")
(def expand-arrows-alternate-icon "expand arrows alternate")
(def expand-icon "expand")
(def expeditedssl-icon "expeditedssl")
(def external-alternate-icon "external alternate")
(def external-icon "external")
(def external-share-icon "external share")
(def external-square-alternate-icon "external square alternate")
(def external-square-icon "external square")
(def eye-dropper-icon "eye dropper")
(def eye-icon "eye")
(def eye-slash-icon "eye slash")
(def eye-slash-outline-icon "eye slash outline")
(def eyedropper-icon "eyedropper")
(def facebook-f-icon "facebook f")
(def facebook-icon "facebook")
(def facebook-messenger-icon "facebook messenger")
(def facebook-official-icon "facebook official")
(def facebook-square-icon "facebook square")
(def factory-icon "factory")
(def fast-backward-icon "fast backward")
(def fast-forward-icon "fast forward")
(def favorite-icon "favorite")
(def fax-icon "fax")
(def feed-icon "feed")
(def female-homosexual-icon "female homosexual")
(def female-icon "female")
(def fighter-jet-icon "fighter jet")
(def file-alternate-icon "file alternate")
(def file-alternate-outline-icon "file alternate outline")
(def file-archive-icon "file archive")
(def file-archive-outline-icon "file archive outline")
(def file-audio-icon "file audio")
(def file-audio-outline-icon "file audio outline")
(def file-code-icon "file code")
(def file-code-outline-icon "file code outline")
(def file-excel-icon "file excel")
(def file-excel-outline-icon "file excel outline")
(def file-icon "file")
(def file-image-icon "file image")
(def file-image-outline-icon "file image outline")
(def file-outline-icon "file outline")
(def file-pdf-icon "file pdf")
(def file-pdf-outline-icon "file pdf outline")
(def file-powerpoint-icon "file powerpoint")
(def file-powerpoint-outline-icon "file powerpoint outline")
(def file-text-icon "file text")
(def file-text-outline-icon "file text outline")
(def file-video-icon "file video")
(def file-video-outline-icon "file video outline")
(def file-word-icon "file word")
(def file-word-outline-icon "file word outline")
(def film-icon "film")
(def filter-icon "filter")
(def find-icon "find")
(def fire-extinguisher-icon "fire extinguisher")
(def fire-icon "fire")
(def firefox-icon "firefox")
(def first-aid-icon "first aid")
(def first-order-icon "first order")
(def firstdraft-icon "firstdraft")
(def flag-checkered-icon "flag checkered")
(def flag-icon "flag")
(def flag-outline-icon "flag outline")
(def flask-icon "flask")
(def flickr-icon "flickr")
(def flipboard-icon "flipboard")
(def fly-icon "fly")
(def folder-icon "folder")
(def folder-open-icon "folder open")
(def folder-open-outline-icon "folder open outline")
(def folder-outline-icon "folder outline")
(def font-awesome-alternate-icon "font awesome alternate")
(def font-awesome-flag-icon "font awesome flag")
(def font-awesome-icon "font awesome")
(def font-icon "font")
(def fonticons-fi-icon "fonticons fi")
(def fonticons-icon "fonticons")
(def food-icon "food")
(def football-ball-icon "football ball")
(def fork-icon "fork")
(def fort-awesome-alternate-icon "fort awesome alternate")
(def fort-awesome-icon "fort awesome")
(def forumbee-icon "forumbee")
(def forward-icon "forward")
(def foursquare-icon "foursquare")
(def free-code-camp-icon "free code camp")
(def freebsd-icon "freebsd")
(def frown-icon "frown")
(def frown-outline-icon "frown outline")
(def futbol-icon "futbol")
(def futbol-outline-icon "futbol outline")
(def game-icon "game")
(def gamepad-icon "gamepad")
(def gavel-icon "gavel")
(def gay-icon "gay")
(def gbp-icon "gbp")
(def gem-icon "gem")
(def gem-outline-icon "gem outline")
(def genderless-icon "genderless")
(def get-pocket-icon "get pocket")
(def gg-circle-icon "gg circle")
(def gg-icon "gg")
(def gift-icon "gift")
(def git-icon "git")
(def git-square-icon "git square")
(def github-alternate-icon "github alternate")
(def github-icon "github")
(def github-square-icon "github square")
(def gitkraken-icon "gitkraken")
(def gitlab-icon "gitlab")
(def gitter-icon "gitter")
(def glass-martini-icon "glass martini")
(def glide-g-icon "glide g")
(def glide-icon "glide")
(def globe-icon "globe")
(def gofore-icon "gofore")
(def golf-ball-icon "golf ball")
(def goodreads-g-icon "goodreads g")
(def goodreads-icon "goodreads")
(def google-drive-icon "google drive")
(def google-icon "google")
(def google-play-icon "google play")
(def google-plus-circle-icon "google plus circle")
(def google-plus-g-icon "google plus g")
(def google-plus-icon "google plus")
(def google-plus-official-icon "google plus official")
(def google-plus-square-icon "google plus square")
(def google-wallet-icon "google wallet")
(def grab-icon "grab")
(def graduation-cap-icon "graduation cap")
(def graduation-icon "graduation")
(def gratipay-icon "gratipay")
(def grav-icon "grav")
(def grid-layout-icon "grid layout")
(def gripfire-icon "gripfire")
(def group-icon "group")
(def grunt-icon "grunt")
(def gulp-icon "gulp")
(def h-icon "h")
(def h-square-icon "h square")
(def hacker-news-icon "hacker news")
(def hacker-news-square-icon "hacker news square")
(def hand-lizard-icon "hand lizard")
(def hand-lizard-outline-icon "hand lizard outline")
(def hand-paper-icon "hand paper")
(def hand-paper-outline-icon "hand paper outline")
(def hand-peace-icon "hand peace")
(def hand-peace-outline-icon "hand peace outline")
(def hand-point-down-icon "hand point down")
(def hand-point-down-outline-icon "hand point down outline")
(def hand-point-left-icon "hand point left")
(def hand-point-left-outline-icon "hand point left outline")
(def hand-point-right-icon "hand point right")
(def hand-point-right-outline-icon "hand point right outline")
(def hand-point-up-icon "hand point up")
(def hand-point-up-outline-icon "hand point up outline")
(def hand-pointer-icon "hand pointer")
(def hand-pointer-outline-icon "hand pointer outline")
(def hand-rock-icon "hand rock")
(def hand-rock-outline-icon "hand rock outline")
(def hand-scissors-icon "hand scissors")
(def hand-scissors-outline-icon "hand scissors outline")
(def hand-spock-icon "hand spock")
(def hand-spock-outline-icon "hand spock outline")
(def hand-victory-icon "hand victory")
(def handicap-icon "handicap")
(def handshake-icon "handshake")
(def handshake-outline-icon "handshake outline")
(def hard-of-hearing-icon "hard of hearing")
(def hashtag-icon "hashtag")
(def hdd-icon "hdd")
(def hdd-outline-icon "hdd outline")
(def header-icon "header")
(def heading-icon "heading")
(def headphones-icon "headphones")
(def heart-icon "heart")
(def heart-outline-icon "heart outline")
(def heartbeat-icon "heartbeat")
(def help-circle-icon "help circle")
(def help-icon "help")
(def heterosexual-icon "heterosexual")
(def hide-icon "hide")
(def hips-icon "hips")
(def hire-a-helper-icon "hire a helper")
(def history-icon "history")
(def hockey-puck-icon "hockey puck")
(def home-icon "home")
(def hooli-icon "hooli")
(def hospital-icon "hospital")
(def hospital-outline-icon "hospital outline")
(def hospital-symbol-icon "hospital symbol")
(def hotel-icon "hotel")
(def hotjar-icon "hotjar")
(def hourglass-end-icon "hourglass end")
(def hourglass-four-icon "hourglass four")
(def hourglass-full-icon "hourglass full")
(def hourglass-half-icon "hourglass half")
(def hourglass-icon "hourglass")
(def hourglass-one-icon "hourglass one")
(def hourglass-outline-icon "hourglass outline")
(def hourglass-start-icon "hourglass start")
(def hourglass-three-icon "hourglass three")
(def hourglass-two-icon "hourglass two")
(def hourglass-zero-icon "hourglass zero")
(def houzz-icon "houzz")
(def html5-icon "html5")
(def hubspot-icon "hubspot")
(def i-cursor-icon "i cursor")
(def id-badge-icon "id badge")
(def id-badge-outline-icon "id badge outline")
(def id-card-icon "id card")
(def id-card-outline-icon "id card outline")
(def idea-icon "idea")
(def ils-icon "ils")
(def image-icon "image")
(def image-outline-icon "image outline")
(def images-icon "images")
(def images-outline-icon "images outline")
(def imdb-icon "imdb")
(def in-cart-icon "in cart")
(def inbox-icon "inbox")
(def indent-icon "indent")
(def industry-icon "industry")
(def info-circle-icon "info circle")
(def info-icon "info")
(def inr-icon "inr")
(def instagram-icon "instagram")
(def intergender-icon "intergender")
(def internet-explorer-icon "internet explorer")
(def intersex-icon "intersex")
(def ioxhost-icon "ioxhost")
(def italic-icon "italic")
(def itunes-icon "itunes")
(def itunes-note-icon "itunes note")
(def jenkins-icon "jenkins")
(def joget-icon "joget")
(def joomla-icon "joomla")
(def jpy-icon "jpy")
(def js-icon "js")
(def js-square-icon "js square")
(def jsfiddle-icon "jsfiddle")
(def key-icon "key")
(def keyboard-icon "keyboard")
(def keyboard-outline-icon "keyboard outline")
(def keycdn-icon "keycdn")
(def kickstarter-icon "kickstarter")
(def kickstarter-k-icon "kickstarter k")
(def korvue-icon "korvue")
(def krw-icon "krw")
(def lab-icon "lab")
(def language-icon "language")
(def laptop-icon "laptop")
(def laravel-icon "laravel")
(def lastfm-icon "lastfm")
(def lastfm-square-icon "lastfm square")
(def law-icon "law")
(def leaf-icon "leaf")
(def leanpub-icon "leanpub")
(def left-dropdown-icon "left dropdown")
(def legal-icon "legal")
(def lemon-icon "lemon")
(def lemon-outline-icon "lemon outline")
(def lesbian-icon "lesbian")
(def less-icon "less")
(def level-down-alternate-icon "level down alternate")
(def level-down-icon "level down")
(def level-up-alternate-icon "level up alternate")
(def level-up-icon "level up")
(def life-ring-icon "life ring")
(def life-ring-outline-icon "life ring outline")
(def lightbulb-icon "lightbulb")
(def lightbulb-outline-icon "lightbulb outline")
(def lightning-icon "lightning")
(def like-icon "like")
(def line-graph-icon "line graph")
(def linechat-icon "linechat")
(def linkedin-alternate-icon "linkedin alternate")
(def linkedin-icon "linkedin")
(def linkedin-square-icon "linkedin square")
(def linkify-icon "linkify")
(def linode-icon "linode")
(def linux-icon "linux")
(def lira-icon "lira")
(def lira-sign-icon "lira sign")
(def list-alternate-icon "list alternate")
(def list-alternate-outline-icon "list alternate outline")
(def list-icon "list")
(def list-layout-icon "list layout")
(def list-ol-icon "list ol")
(def list-ul-icon "list ul")
(def location-arrow-icon "location arrow")
(def lock-icon "lock")
(def lock-open-icon "lock open")
(def log-out-icon "log out")
(def long-arrow-alternate-down-icon "long arrow alternate down")
(def long-arrow-alternate-left-icon "long arrow alternate left")
(def long-arrow-alternate-right-icon "long arrow alternate right")
(def long-arrow-alternate-up-icon "long arrow alternate up")
(def low-vision-icon "low vision")
(def lyft-icon "lyft")
(def magento-icon "magento")
(def magic-icon "magic")
(def magnet-icon "magnet")
(def magnify-icon "magnify")
(def mail-forward-icon "mail forward")
(def mail-icon "mail")
(def mail-square-icon "mail square")
(def male-homosexual-icon "male homosexual")
(def male-icon "male")
(def man-icon "man")
(def map-icon "map")
(def map-marker-alternate-icon "map marker alternate")
(def map-marker-icon "map marker")
(def map-outline-icon "map outline")
(def map-pin-icon "map pin")
(def map-signs-icon "map signs")
(def marker-icon "marker")
(def mars-alternate-icon "mars alternate")
(def mars-double-icon "mars double")
(def mars-horizontal-icon "mars horizontal")
(def mars-icon "mars")
(def mars-stroke-horizontal-icon "mars stroke horizontal")
(def mars-stroke-icon "mars stroke")
(def mars-stroke-vertical-icon "mars stroke vertical")
(def mars-vertical-icon "mars vertical")
(def maxcdn-icon "maxcdn")
(def meanpath-icon "meanpath")
(def medapps-icon "medapps")
(def medium-icon "medium")
(def medium-m-icon "medium m")
(def medkit-icon "medkit")
(def medrt-icon "medrt")
(def meetup-icon "meetup")
(def meh-icon "meh")
(def meh-outline-icon "meh outline")
(def mercury-icon "mercury")
(def microchip-icon "microchip")
(def microphone-icon "microphone")
(def microphone-slash-icon "microphone slash")
(def microsoft-edge-icon "microsoft edge")
(def microsoft-icon "microsoft")
(def military-icon "military")
(def minus-circle-icon "minus circle")
(def minus-icon "minus")
(def minus-square-icon "minus square")
(def minus-square-outline-icon "minus square outline")
(def mix-icon "mix")
(def mixcloud-icon "mixcloud")
(def mizuni-icon "mizuni")
(def mobile-alternate-icon "mobile alternate")
(def mobile-icon "mobile")
(def modx-icon "modx")
(def monero-icon "monero")
(def money-bill-alternate-icon "money bill alternate")
(def money-bill-alternate-outline-icon "money bill alternate outline")
(def money-icon "money")
(def moon-icon "moon")
(def moon-outline-icon "moon outline")
(def motorcycle-icon "motorcycle")
(def mouse-pointer-icon "mouse pointer")
(def move-icon "move")
(def ms-edge-icon "ms edge")
(def music-icon "music")
(def mute-icon "mute")
(def napster-icon "napster")
(def neuter-icon "neuter")
(def new-pied-piper-icon "new pied piper")
(def newspaper-icon "newspaper")
(def newspaper-outline-icon "newspaper outline")
(def nintendo-switch-icon "nintendo switch")
(def node-icon "node")
(def node-js-icon "node js")
(def non-binary-transgender-icon "non binary transgender")
(def npm-icon "npm")
(def ns8-icon "ns8")
(def numbered-list-icon "numbered list")
(def nutritionix-icon "nutritionix")
(def object-group-icon "object group")
(def object-group-outline-icon "object group outline")
(def object-ungroup-icon "object ungroup")
(def object-ungroup-outline-icon "object ungroup outline")
(def odnoklassniki-icon "odnoklassniki")
(def odnoklassniki-square-icon "odnoklassniki square")
(def opencart-icon "opencart")
(def openid-icon "openid")
(def opera-icon "opera")
(def optin-monster-icon "optin monster")
(def options-icon "options")
(def ordered-list-icon "ordered list")
(def osi-icon "osi")
(def other-gender-horizontal-icon "other gender horizontal")
(def other-gender-icon "other gender")
(def other-gender-vertical-icon "other gender vertical")
(def outdent-icon "outdent")
(def page4-icon "page4")
(def pagelines-icon "pagelines")
(def paint-brush-icon "paint brush")
(def palfed-icon "palfed")
(def pallet-icon "pallet")
(def paper-plane-icon "paper plane")
(def paper-plane-outline-icon "paper plane outline")
(def paperclip-icon "paperclip")
(def paragraph-icon "paragraph")
(def paste-icon "paste")
(def patreon-icon "patreon")
(def pause-circle-icon "pause circle")
(def pause-circle-outline-icon "pause circle outline")
(def pause-icon "pause")
(def paw-icon "paw")
(def payment-icon "payment")
(def paypal-card-icon "paypal card")
(def paypal-icon "paypal")
(def pen-square-icon "pen square")
(def pencil-alternate-icon "pencil alternate")
(def pencil-icon "pencil")
(def pencil-square-icon "pencil square")
(def percent-icon "percent")
(def periscope-icon "periscope")
(def phabricator-icon "phabricator")
(def phoenix-framework-icon "phoenix framework")
(def phone-icon "phone")
(def phone-square-icon "phone square")
(def phone-volume-icon "phone volume")
(def photo-icon "photo")
(def php-icon "php")
(def picture-icon "picture")
(def pie-chart-icon "pie chart")
(def pie-graph-icon "pie graph")
(def pied-piper-alternate-icon "pied piper alternate")
(def pied-piper-hat-icon "pied piper hat")
(def pied-piper-icon "pied piper")
(def pied-piper-pp-icon "pied piper pp")
(def pills-icon "pills")
(def pin-icon "pin")
(def pinterest-icon "pinterest")
(def pinterest-p-icon "pinterest p")
(def pinterest-square-icon "pinterest square")
(def plane-icon "plane")
(def play-circle-icon "play circle")
(def play-circle-outline-icon "play circle outline")
(def play-icon "play")
(def playstation-icon "playstation")
(def plug-icon "plug")
(def plus-cart-icon "plus cart")
(def plus-circle-icon "plus circle")
(def plus-icon "plus")
(def plus-square-icon "plus square")
(def plus-square-outline-icon "plus square outline")
(def podcast-icon "podcast")
(def point-icon "point")
(def pointing-down-icon "pointing down")
(def pointing-left-icon "pointing left")
(def pointing-right-icon "pointing right")
(def pointing-up-icon "pointing up")
(def pound-icon "pound")
(def pound-sign-icon "pound sign")
(def power-cord-icon "power cord")
(def power-icon "power")
(def power-off-icon "power off")
(def print-icon "print")
(def privacy-icon "privacy")
(def product-hunt-icon "product hunt")
(def protect-icon "protect")
(def pushed-icon "pushed")
(def puzzle-icon "puzzle")
(def puzzle-piece-icon "puzzle piece")
(def python-icon "python")
(def qq-icon "qq")
(def qrcode-icon "qrcode")
(def question-circle-icon "question circle")
(def question-circle-outline-icon "question circle outline")
(def question-icon "question")
(def quidditch-icon "quidditch")
(def quinscape-icon "quinscape")
(def quora-icon "quora")
(def quote-left-icon "quote left")
(def quote-right-icon "quote right")
(def r-circle-icon "r circle")
(def radio-icon "radio")
(def rain-icon "rain")
(def random-icon "random")
(def ravelry-icon "ravelry")
(def react-icon "react")
(def rebel-icon "rebel")
(def record-icon "record")
(def recycle-icon "recycle")
(def reddit-alien-icon "reddit alien")
(def reddit-icon "reddit")
(def reddit-square-icon "reddit square")
(def redo-alternate-icon "redo alternate")
(def redo-icon "redo")
(def redriver-icon "redriver")
(def refresh-icon "refresh")
(def registered-icon "registered")
(def registered-outline-icon "registered outline")
(def remove-bookmark-icon "remove bookmark")
(def remove-circle-icon "remove circle")
(def remove-from-calendar-icon "remove from calendar")
(def remove-icon "remove")
(def remove-user-icon "remove user")
(def rendact-icon "rendact")
(def renren-icon "renren")
(def repeat-icon "repeat")
(def reply-all-icon "reply all")
(def reply-icon "reply")
(def replyd-icon "replyd")
(def resize-horizontal-icon "resize horizontal")
(def resize-vertical-icon "resize vertical")
(def resolving-icon "resolving")
(def retweet-icon "retweet")
(def rmb-icon "rmb")
(def road-icon "road")
(def rocket-icon "rocket")
(def rocketchat-icon "rocketchat")
(def rockrms-icon "rockrms")
(def rouble-icon "rouble")
(def rss-icon "rss")
(def rss-square-icon "rss square")
(def rub-icon "rub")
(def ruble-icon "ruble")
(def ruble-sign-icon "ruble sign")
(def rupee-icon "rupee")
(def rupee-sign-icon "rupee sign")
(def s15-icon "s15")
(def safari-icon "safari")
(def sass-icon "sass")
(def save-icon "save")
(def save-outline-icon "save outline")
(def schlix-icon "schlix")
(def scribd-icon "scribd")
(def search-icon "search")
(def search-minus-icon "search minus")
(def search-plus-icon "search plus")
(def searchengin-icon "searchengin")
(def selected-radio-icon "selected radio")
(def sellcast-icon "sellcast")
(def sellsy-icon "sellsy")
(def send-icon "send")
(def server-icon "server")
(def servicestack-icon "servicestack")
(def setting-icon "setting")
(def settings-icon "settings")
(def share-alternate-icon "share alternate")
(def share-alternate-square-icon "share alternate square")
(def share-icon "share")
(def share-square-icon "share square")
(def share-square-outline-icon "share square outline")
(def shekel-icon "shekel")
(def shekel-sign-icon "shekel sign")
(def sheqel-icon "sheqel")
(def shield-alternate-icon "shield alternate")
(def shield-icon "shield")
(def ship-icon "ship")
(def shipping-fast-icon "shipping fast")
(def shipping-icon "shipping")
(def shirtsinbulk-icon "shirtsinbulk")
(def shop-icon "shop")
(def shopping-bag-icon "shopping bag")
(def shopping-basket-icon "shopping basket")
(def shopping-cart-icon "shopping cart")
(def shower-icon "shower")
(def shuffle-icon "shuffle")
(def shutdown-icon "shutdown")
(def sidebar-icon "sidebar")
(def sign-in-alternate-icon "sign in alternate")
(def sign-in-icon "sign in")
(def sign-language-icon "sign language")
(def sign-out-alternate-icon "sign out alternate")
(def sign-out-icon "sign out")
(def signal-icon "signal")
(def signing-icon "signing")
(def signup-icon "signup")
(def simplybuilt-icon "simplybuilt")
(def sistrix-icon "sistrix")
(def sitemap-icon "sitemap")
(def skyatlas-icon "skyatlas")
(def skype-icon "skype")
(def slack-hash-icon "slack hash")
(def slack-icon "slack")
(def sliders-horizontal-icon "sliders horizontal")
(def sliders-icon "sliders")
(def slideshare-icon "slideshare")
(def smile-icon "smile")
(def smile-outline-icon "smile outline")
(def snapchat-ghost-icon "snapchat ghost")
(def snapchat-icon "snapchat")
(def snapchat-square-icon "snapchat square")
(def snowflake-icon "snowflake")
(def snowflake-outline-icon "snowflake outline")
(def soccer-icon "soccer")
(def sort-alphabet-ascending-icon "sort alphabet ascending")
(def sort-alphabet-descending-icon "sort alphabet descending")
(def sort-alphabet-down-icon "sort alphabet down")
(def sort-alphabet-up-icon "sort alphabet up")
(def sort-amount-down-icon "sort amount down")
(def sort-amount-up-icon "sort amount up")
(def sort-ascending-icon "sort ascending")
(def sort-content-ascending-icon "sort content ascending")
(def sort-content-descending-icon "sort content descending")
(def sort-descending-icon "sort descending")
(def sort-down-icon "sort down")
(def sort-icon "sort")
(def sort-numeric-ascending-icon "sort numeric ascending")
(def sort-numeric-descending-icon "sort numeric descending")
(def sort-numeric-down-icon "sort numeric down")
(def sort-numeric-up-icon "sort numeric up")
(def sort-up-icon "sort up")
(def sound-icon "sound")
(def soundcloud-icon "soundcloud")
(def space-shuttle-icon "space shuttle")
(def speakap-icon "speakap")
(def spinner-icon "spinner")
(def spoon-icon "spoon")
(def spotify-icon "spotify")
(def spy-icon "spy")
(def square-full-icon "square full")
(def square-icon "square")
(def square-outline-icon "square outline")
(def stack-exchange-icon "stack exchange")
(def stack-overflow-icon "stack overflow")
(def star-half-empty-icon "star half empty")
(def star-half-full-icon "star half full")
(def star-half-icon "star half")
(def star-half-outline-icon "star half outline")
(def star-icon "star")
(def star-outline-icon "star outline")
(def staylinked-icon "staylinked")
(def steam-icon "steam")
(def steam-square-icon "steam square")
(def steam-symbol-icon "steam symbol")
(def step-backward-icon "step backward")
(def step-forward-icon "step forward")
(def stethoscope-icon "stethoscope")
(def sticker-mule-icon "sticker mule")
(def sticky-note-icon "sticky note")
(def sticky-note-outline-icon "sticky note outline")
(def stop-circle-icon "stop circle")
(def stop-circle-outline-icon "stop circle outline")
(def stop-icon "stop")
(def stopwatch-icon "stopwatch")
(def strava-icon "strava")
(def street-view-icon "street view")
(def strikethrough-icon "strikethrough")
(def stripe-card-icon "stripe card")
(def stripe-icon "stripe")
(def stripe-s-icon "stripe s")
(def student-icon "student")
(def studiovinari-icon "studiovinari")
(def stumbleupon-circle-icon "stumbleupon circle")
(def stumbleupon-icon "stumbleupon")
(def subscript-icon "subscript")
(def subway-icon "subway")
(def suitcase-icon "suitcase")
(def sun-icon "sun")
(def sun-outline-icon "sun outline")
(def superpowers-icon "superpowers")
(def superscript-icon "superscript")
(def supple-icon "supple")
(def sync-alternate-icon "sync alternate")
(def sync-icon "sync")
(def syringe-icon "syringe")
(def table-icon "table")
(def table-tennis-icon "table tennis")
(def tablet-alternate-icon "tablet alternate")
(def tablet-icon "tablet")
(def tachometer-alternate-icon "tachometer alternate")
(def tag-icon "tag")
(def tags-icon "tags")
(def talk-icon "talk")
(def target-icon "target")
(def tasks-icon "tasks")
(def taxi-icon "taxi")
(def telegram-icon "telegram")
(def telegram-plane-icon "telegram plane")
(def teletype-icon "teletype")
(def television-icon "television")
(def tencent-weibo-icon "tencent weibo")
(def terminal-icon "terminal")
(def text-cursor-icon "text cursor")
(def text-height-icon "text height")
(def text-telephone-icon "text telephone")
(def text-width-icon "text width")
(def th-icon "th")
(def th-large-icon "th large")
(def th-list-icon "th list")
(def theme-icon "theme")
(def themeisle-icon "themeisle")
(def thermometer-empty-icon "thermometer empty")
(def thermometer-full-icon "thermometer full")
(def thermometer-half-icon "thermometer half")
(def thermometer-icon "thermometer")
(def thermometer-quarter-icon "thermometer quarter")
(def thermometer-three-quarters-icon "thermometer three quarters")
(def thumb-tack-icon "thumb tack")
(def thumbs-down-icon "thumbs down")
(def thumbs-down-outline-icon "thumbs down outline")
(def thumbs-up-icon "thumbs up")
(def thumbs-up-outline-icon "thumbs up outline")
(def thumbtack-icon "thumbtack")
(def ticket-alternate-icon "ticket alternate")
(def ticket-icon "ticket")
(def time-icon "time")
(def times-circle-icon "times circle")
(def times-circle-outline-icon "times circle outline")
(def times-icon "times")
(def times-rectangle-icon "times rectangle")
(def tint-icon "tint")
(def tm-icon "tm")
(def toggle-down-icon "toggle down")
(def toggle-left-icon "toggle left")
(def toggle-off-icon "toggle off")
(def toggle-on-icon "toggle on")
(def toggle-right-icon "toggle right")
(def toggle-up-icon "toggle up")
(def trademark-icon "trademark")
(def train-icon "train")
(def transgender-alternate-icon "transgender alternate")
(def transgender-icon "transgender")
(def translate-icon "translate")
(def trash-alternate-icon "trash alternate")
(def trash-alternate-outline-icon "trash alternate outline")
(def trash-icon "trash")
(def travel-icon "travel")
(def treatment-icon "treatment")
(def tree-icon "tree")
(def trello-icon "trello")
(def triangle-down-icon "triangle down")
(def triangle-left-icon "triangle left")
(def triangle-right-icon "triangle right")
(def triangle-up-icon "triangle up")
(def tripadvisor-icon "tripadvisor")
(def trophy-icon "trophy")
(def truck-icon "truck")
(def try-icon "try")
(def tty-icon "tty")
(def tumblr-icon "tumblr")
(def tumblr-square-icon "tumblr square")
(def tv-icon "tv")
(def twitch-icon "twitch")
(def twitter-icon "twitter")
(def twitter-square-icon "twitter square")
(def typo3-icon "typo3")
(def uber-icon "uber")
(def uikit-icon "uikit")
(def umbrella-icon "umbrella")
(def underline-icon "underline")
(def undo-alternate-icon "undo alternate")
(def undo-icon "undo")
(def unhide-icon "unhide")
(def uniregistry-icon "uniregistry")
(def universal-access-icon "universal access")
(def university-icon "university")
(def unlink-icon "unlink")
(def unlinkify-icon "unlinkify")
(def unlock-alternate-icon "unlock alternate")
(def unlock-icon "unlock")
(def unmute-icon "unmute")
(def unordered-list-icon "unordered list")
(def untappd-icon "untappd")
(def upload-icon "upload")
(def usb-icon "usb")
(def usd-icon "usd")
(def user-cancel-icon "user cancel")
(def user-circle-icon "user circle")
(def user-circle-outline-icon "user circle outline")
(def user-close-icon "user close")
(def user-delete-icon "user delete")
(def user-doctor-icon "user doctor")
(def user-icon "user")
(def user-md-icon "user md")
(def user-outline-icon "user outline")
(def user-plus-icon "user plus")
(def user-secret-icon "user secret")
(def user-times-icon "user times")
(def user-x-icon "user x")
(def users-icon "users")
(def ussunnah-icon "ussunnah")
(def utensil-spoon-icon "utensil spoon")
(def utensils-icon "utensils")
(def vaadin-icon "vaadin")
(def vcard-icon "vcard")
(def venus-double-icon "venus double")
(def venus-icon "venus")
(def venus-mars-icon "venus mars")
(def viacoin-icon "viacoin")
(def viadeo-icon "viadeo")
(def viadeo-square-icon "viadeo square")
(def viber-icon "viber")
(def video-camera-icon "video camera")
(def video-icon "video")
(def video-play-icon "video play")
(def vimeo-icon "vimeo")
(def vimeo-square-icon "vimeo square")
(def vimeo-v-icon "vimeo v")
(def vine-icon "vine")
(def vk-icon "vk")
(def vnv-icon "vnv")
(def volleyball-ball-icon "volleyball ball")
(def volume-control-phone-icon "volume control phone")
(def volume-down-icon "volume down")
(def volume-off-icon "volume off")
(def volume-up-icon "volume up")
(def vuejs-icon "vuejs")
(def wait-icon "wait")
(def warehouse-icon "warehouse")
(def warning-circle-icon "warning circle")
(def warning-icon "warning")
(def warning-sign-icon "warning sign")
(def wechat-icon "wechat")
(def weibo-icon "weibo")
(def weight-icon "weight")
(def weixin-icon "weixin")
(def whatsapp-icon "whatsapp")
(def whatsapp-square-icon "whatsapp square")
(def wheelchair-icon "wheelchair")
(def whmcs-icon "whmcs")
(def wi-fi-icon "wi fi")
(def wifi-icon "wifi")
(def wikipedia-w-icon "wikipedia w")
(def window-close-icon "window close")
(def window-close-outline-icon "window close outline")
(def window-maximize-icon "window maximize")
(def window-maximize-outline-icon "window maximize outline")
(def window-minimize-icon "window minimize")
(def window-minimize-outline-icon "window minimize outline")
(def window-restore-icon "window restore")
(def window-restore-outline-icon "window restore outline")
(def windows-icon "windows")
(def winner-icon "winner")
(def wizard-icon "wizard")
(def woman-icon "woman")
(def won-icon "won")
(def won-sign-icon "won sign")
(def wordpress-beginner-icon "wordpress beginner")
(def wordpress-forms-icon "wordpress forms")
(def wordpress-icon "wordpress")
(def wordpress-simple-icon "wordpress simple")
(def world-icon "world")
(def wpbeginner-icon "wpbeginner")
(def wpexplorer-icon "wpexplorer")
(def wpforms-icon "wpforms")
(def wrench-icon "wrench")
(def write-icon "write")
(def write-square-icon "write square")
(def x-icon "x")
(def xbox-icon "xbox")
(def xing-icon "xing")
(def xing-square-icon "xing square")
(def y-combinator-icon "y combinator")
(def yahoo-icon "yahoo")
(def yandex-icon "yandex")
(def yandex-international-icon "yandex international")
(def yelp-icon "yelp")
(def yen-icon "yen")
(def yen-sign-icon "yen sign")
(def yoast-icon "yoast")
(def youtube-icon "youtube")
(def youtube-play-icon "youtube play")
(def youtube-square-icon "youtube square")
(def zip-icon "zip")
(def zoom-icon "zoom")
(def zoom-in-icon "zoom in")
(def zoom-out-icon "zoom out")
