(ns fulcrologic.semantic-ui.icons)

(def add-circle-icon "add circle")
(def add-square-icon "add square")
(def add-to-calendar-icon "add to calendar")
(def add-to-cart-icon "add to cart")
(def add-user-icon "add user")
(def add-icon "add")
(def address-book-outline-icon "address book outline")
(def address-book-icon "address book")
(def address-card-outline-icon "address card outline")
(def address-card-icon "address card")
(def adjust-icon "adjust")
(def adn-icon "adn")

(def alarm-mute-outline-icon "alarm mute outline")
(def alarm-mute-icon "alarm mute")
(def alarm-outline-icon "alarm outline")
(def alarm-icon "alarm")
(def ald-icon "ald")
(def align-center-icon "align center")
(def align-justify-icon "align justify")

(def align-left-icon "align left")
(def align-right-icon "align right")
(def als-icon "als")
(def amazon-icon "amazon")
(def ambulance-icon "ambulance")
(def american-express-card-icon "american express card")
(def american-express-icon "american express")

(def american-sign-language-interpreting-icon "american sign language interpreting")
(def amex-icon "amex")
(def anchor-icon "anchor")
(def android-icon "android")
(def angellist-icon "angellist")
(def angle-double-down-icon "angle double down")
(def angle-double-left-icon "angle double left")

(def angle-double-right-icon "angle double right")
(def angle-double-up-icon "angle double up")
(def angle-down-icon "angle down")
(def angle-left-icon "angle left")
(def angle-right-icon "angle right")
(def angle-up-icon "angle up")
(def announcement-icon "announcement")

(def apple-icon "apple")
(def archive-icon "archive")
(def area-chart-icon "area chart")
(def area-graph-icon "area graph")
(def arrow-circle-down-icon "arrow circle down")
(def arrow-circle-left-icon "arrow circle left")
(def arrow-circle-outline-down-icon "arrow circle outline down")

(def arrow-circle-outline-left-icon "arrow circle outline left")
(def arrow-circle-outline-right-icon "arrow circle outline right")
(def arrow-circle-outline-up-icon "arrow circle outline up")
(def arrow-circle-right-icon "arrow circle right")
(def arrow-circle-up-icon "arrow circle up")
(def arrow-down-cart-icon "arrow down cart")
(def arrow-down-icon "arrow down")

(def arrow-left-icon "arrow left")
(def arrow-right-icon "arrow right")
(def arrow-up-icon "arrow up")
(def asexual-icon "asexual")
(def asl-interpreting-icon "asl interpreting")
(def asl-icon "asl")
(def assistive-listening-devices-icon "assistive listening devices")

(def assistive-listening-systems-icon "assistive listening systems")
(def asterisk-icon "asterisk")
(def at-icon "at")
(def attach-icon "attach")
(def attention-icon "attention")
(def audio-description-icon "audio description")
(def backward-icon "backward")

(def balance-icon "balance")
(def ban-icon "ban")
(def bandcamp-icon "bandcamp")
(def bar-chart-icon "bar chart")
(def bar-graph-icon "bar graph")
(def bar-icon "bar")
(def barcode-icon "barcode")

(def bars-icon "bars")
(def bath-icon "bath")
(def bathtub-icon "bathtub")
(def battery-empty-icon "battery empty")
(def battery-four-icon "battery four")
(def battery-full-icon "battery full")
(def battery-half-icon "battery half")

(def battery-high-icon "battery high")
(def battery-low-icon "battery low")
(def battery-medium-icon "battery medium")
(def battery-one-icon "battery one")
(def battery-quarter-icon "battery quarter")
(def battery-three-quarters-icon "battery three quarters")
(def battery-three-icon "battery three")

(def battery-two-icon "battery two")
(def battery-zero-icon "battery zero")
(def bed-icon "bed")
(def beer-icon "beer")
(def behance-square-icon "behance square")
(def behance-icon "behance")
(def bell-outline-icon "bell outline")

(def bell-slash-outline-icon "bell slash outline")
(def bell-slash-icon "bell slash")
(def bell-icon "bell")
(def bicycle-icon "bicycle")
(def binoculars-icon "binoculars")
(def birthday-icon "birthday")
(def bitbucket-square-icon "bitbucket square")

(def bitbucket-icon "bitbucket")
(def bitcoin-icon "bitcoin")
(def black-tie-icon "black tie")
(def blind-icon "blind")
(def block-layout-icon "block layout")
(def bluetooth-alternative-icon "bluetooth alternative")
(def bluetooth-icon "bluetooth")

(def bold-icon "bold")
(def bomb-icon "bomb")
(def book-icon "book")
(def bookmark-outline-icon "bookmark outline")
(def bookmark-icon "bookmark")
(def braille-icon "braille")
(def briefcase-icon "briefcase")

(def broken-chain-icon "broken chain")
(def browser-icon "browser")
(def btc-icon "btc")
(def bug-icon "bug")
(def building-outline-icon "building outline")
(def building-icon "building")
(def bullhorn-icon "bullhorn")

(def bullseye-icon "bullseye")
(def bus-icon "bus")
(def buysellads-icon "buysellads")
(def calculator-icon "calculator")
(def calendar-check-icon "calendar check")
(def calendar-minus-icon "calendar minus")
(def calendar-outline-icon "calendar outline")

(def calendar-plus-icon "calendar plus")
(def calendar-times-icon "calendar times")
(def calendar-icon "calendar")
(def call-square-icon "call square")
(def call-icon "call")
(def camera-retro-icon "camera retro")
(def camera-icon "camera")

(def cancel-icon "cancel")
(def car-icon "car")
(def caret-down-icon "caret down")
(def caret-left-icon "caret left")
(def caret-right-icon "caret right")
(def caret-up-icon "caret up")
(def cart-icon "cart")

(def cc-icon "cc")
(def certificate-icon "certificate")
(def chain-icon "chain")
(def chat-icon "chat")
(def check-circle-outline-icon "check circle outline")
(def check-circle-icon "check circle")
(def check-square-icon "check square")

(def check-icon "check")
(def checked-calendar-icon "checked calendar")
(def checkmark-box-icon "checkmark box")
(def checkmark-icon "checkmark")
(def chevron-circle-down-icon "chevron circle down")
(def chevron-circle-left-icon "chevron circle left")
(def chevron-circle-right-icon "chevron circle right")

(def chevron-circle-up-icon "chevron circle up")
(def chevron-down-icon "chevron down")
(def chevron-left-icon "chevron left")
(def chevron-right-icon "chevron right")
(def chevron-up-icon "chevron up")
(def child-icon "child")
(def chrome-icon "chrome")

(def circle-notched-icon "circle notched")
(def circle-outline-icon "circle outline")
(def circle-thin-icon "circle thin")
(def circle-icon "circle")
(def clipboard-icon "clipboard")
(def clock-icon "clock")
(def clone-icon "clone")

(def close-icon "close")
(def closed-captioning-icon "closed captioning")
(def cloud-download-icon "cloud download")
(def cloud-upload-icon "cloud upload")
(def cloud-icon "cloud")
(def cny-icon "cny")
(def cocktail-icon "cocktail")

(def code-icon "code")
(def codepen-icon "codepen")
(def codiepie-icon "codiepie")
(def coffee-icon "coffee")
(def cogs-icon "cogs")
(def columns-icon "columns")
(def comment-outline-icon "comment outline")

(def comment-icon "comment")
(def commenting-outline-icon "commenting outline")
(def commenting-icon "commenting")
(def comments-outline-icon "comments outline")
(def comments-icon "comments")
(def compass-icon "compass")
(def compose-icon "compose")

(def compress-icon "compress")
(def computer-icon "computer")
(def configure-icon "configure")
(def connectdevelop-icon "connectdevelop")
(def contao-icon "contao")
(def content-icon "content")
(def conversation-icon "conversation")

(def copy-icon "copy")
(def copyright-icon "copyright")
(def creative-commons-icon "creative commons")
(def credit-card-alternative-icon "credit card alternative")
(def credit-card-icon "credit card")
(def crop-icon "crop")
(def crosshairs-icon "crosshairs")

(def css3-icon "css3")
(def cube-icon "cube")
(def cubes-icon "cubes")
(def currency-icon "currency")
(def cut-icon "cut")
(def dashboard-icon "dashboard")
(def dashcube-icon "dashcube")

(def database-icon "database")
(def deaf-icon "deaf")
(def deafness-icon "deafness")
(def delete-calendar-icon "delete calendar")
(def delete-icon "delete")
(def delicious-icon "delicious")
(def desktop-icon "desktop")

(def detective-icon "detective")
(def deviantart-icon "deviantart")
(def diamond-icon "diamond")
(def digg-icon "digg")
(def diners-club-card-icon "diners club card")
(def diners-club-icon "diners club")
(def discover-card-icon "discover card")

(def discover-icon "discover")
(def discussions-icon "discussions")
(def disk-outline-icon "disk outline")
(def dislike-outline-icon "dislike outline")
(def doctor-icon "doctor")
(def dollar-icon "dollar")
(def dont-icon "dont")

(def dot-circle-outline-icon "dot circle outline")
(def download-icon "download")
(def dribble-icon "dribble")
(def drivers-license-outline-icon "drivers license outline")
(def drivers-license-icon "drivers license")
(def dropbox-icon "dropbox")
(def dropdown-icon "dropdown")

(def drupal-icon "drupal")
(def edge-icon "edge")
(def edit-icon "edit")
(def eercast-icon "eercast")
(def eject-icon "eject")
(def ellipsis-horizontal-icon "ellipsis horizontal")
(def ellipsis-vertical-icon "ellipsis vertical")

(def emergency-icon "emergency")
(def empire-icon "empire")
(def empty-heart-icon "empty heart")
(def empty-star-icon "empty star")
(def envelope-icon "envelope")
(def envira-gallery-icon "envira gallery")
(def envira-icon "envira")

(def erase-icon "erase")
(def eraser-icon "eraser")
(def etsy-icon "etsy")
(def eur-icon "eur")
(def euro-icon "euro")
(def exchange-icon "exchange")
(def exclamation-circle-icon "exclamation circle")

(def exclamation-triangle-icon "exclamation triangle")
(def exclamation-icon "exclamation")
(def expand-icon "expand")
(def expeditedssl-icon "expeditedssl")
(def external-share-icon "external share")
(def external-square-icon "external square")
(def external-icon "external")

(def eye-icon "eye")
(def eyedropper-icon "eyedropper")
(def fa-icon "fa")
(def facebook-f-icon "facebook f")
(def facebook-official-icon "facebook official")
(def facebook-square-icon "facebook square")
(def facebook-icon "facebook")

(def factory-icon "factory")
(def fast-backward-icon "fast backward")
(def fast-forward-icon "fast forward")
(def favorite-icon "favorite")
(def fax-icon "fax")
(def feed-icon "feed")
(def female-homosexual-icon "female homosexual")

(def female-icon "female")
(def fighter-jet-icon "fighter jet")
(def file-archive-outline-icon "file archive outline")
(def file-audio-outline-icon "file audio outline")
(def file-code-outline-icon "file code outline")
(def file-excel-outline-icon "file excel outline")
(def file-image-outline-icon "file image outline")

(def file-outline-icon "file outline")
(def file-pdf-outline-icon "file pdf outline")
(def file-powerpoint-outline-icon "file powerpoint outline")
(def file-text-outline-icon "file text outline")
(def file-text-icon "file text")
(def file-video-outline-icon "file video outline")
(def file-word-outline-icon "file word outline")

(def file-icon "file")
(def film-icon "film")
(def filter-icon "filter")
(def find-icon "find")
(def fire-extinguisher-icon "fire extinguisher")
(def fire-icon "fire")
(def firefox-icon "firefox")

(def first-aid-icon "first aid")
(def first-order-icon "first order")
(def five-hundred-pixels-icon "five hundred pixels")
(def flag-checkered-icon "flag checkered")
(def flag-outline-icon "flag outline")
(def flag-icon "flag")
(def flask-icon "flask")

(def flickr-icon "flickr")
(def folder-open-outline-icon "folder open outline")
(def folder-open-icon "folder open")
(def folder-outline-icon "folder outline")
(def folder-icon "folder")
(def font-awesome-icon "font awesome")
(def font-icon "font")

(def fonticons-icon "fonticons")
(def food-icon "food")
(def fork-icon "fork")
(def fort-awesome-icon "fort awesome")
(def forumbee-icon "forumbee")
(def forward-icon "forward")
(def foursquare-icon "foursquare")

(def free-code-camp-icon "free code camp")
(def frown-icon "frown")
(def game-icon "game")
(def gamepad-icon "gamepad")
(def gay-icon "gay")
(def gbp-icon "gbp")
(def genderless-icon "genderless")

(def gg-circle-icon "gg circle")
(def gg-icon "gg")
(def gift-icon "gift")
(def git-square-icon "git square")
(def git-icon "git")
(def github-alternate-icon "github alternate")
(def github-square-icon "github square")

(def github-icon "github")
(def gitlab-icon "gitlab")
(def gittip-icon "gittip")
(def glide-g-icon "glide g")
(def glide-icon "glide")
(def globe-icon "globe")
(def google-plus-circle-icon "google plus circle")

(def google-plus-official-icon "google plus official")
(def google-plus-square-icon "google plus square")
(def google-plus-icon "google plus")
(def google-wallet-icon "google wallet")
(def google-icon "google")
(def grab-icon "grab")
(def graduation-icon "graduation")

(def gratipay-icon "gratipay")
(def grav-icon "grav")
(def grid-layout-icon "grid layout")
(def group-icon "group")
(def h-icon "h")
(def hacker-news-icon "hacker news")
(def hand-lizard-icon "hand lizard")

(def hand-outline-down-icon "hand outline down")
(def hand-outline-left-icon "hand outline left")
(def hand-outline-right-icon "hand outline right")
(def hand-outline-up-icon "hand outline up")
(def hand-paper-icon "hand paper")
(def hand-peace-icon "hand peace")
(def hand-pointer-icon "hand pointer")

(def hand-rock-icon "hand rock")
(def hand-scissors-icon "hand scissors")
(def hand-spock-icon "hand spock")
(def hand-victory-icon "hand victory")
(def handicap-icon "handicap")
(def hard-of-hearing-icon "hard of hearing")
(def hashtag-icon "hashtag")

(def hdd-outline-icon "hdd outline")
(def header-icon "header")
(def headphone-icon "headphone")
(def heart-outline-icon "heart outline")
(def heart-icon "heart")
(def heartbeat-icon "heartbeat")
(def help-circle-outline-icon "help circle outline")

(def help-circle-icon "help circle")
(def help-icon "help")
(def heterosexual-icon "heterosexual")
(def hide-icon "hide")
(def history-icon "history")
(def home-icon "home")
(def hospital-icon "hospital")

(def hotel-icon "hotel")
(def hourglass-empty-icon "hourglass empty")
(def hourglass-end-icon "hourglass end")
(def hourglass-four-icon "hourglass four")
(def hourglass-full-icon "hourglass full")
(def hourglass-half-icon "hourglass half")
(def hourglass-one-icon "hourglass one")

(def hourglass-outline-icon "hourglass outline")
(def hourglass-start-icon "hourglass start")
(def hourglass-three-icon "hourglass three")
(def hourglass-two-icon "hourglass two")
(def hourglass-zero-icon "hourglass zero")
(def houzz-icon "houzz")
(def html5-icon "html5")

(def i-cursor-icon "i cursor")
(def id-badge-icon "id badge")
(def id-card-outline-icon "id card outline")
(def id-card-icon "id card")
(def idea-icon "idea")
(def ils-icon "ils")
(def image-icon "image")

(def imdb-icon "imdb")
(def in-cart-icon "in cart")
(def inbox-icon "inbox")
(def indent-icon "indent")
(def industry-icon "industry")
(def info-circle-icon "info circle")
(def info-icon "info")

(def inr-icon "inr")
(def instagram-icon "instagram")
(def intergender-icon "intergender")
(def internet-explorer-icon "internet explorer")
(def intersex-icon "intersex")
(def ioxhost-icon "ioxhost")
(def italic-icon "italic")

(def japan-credit-bureau-card-icon "japan credit bureau card")
(def japan-credit-bureau-icon "japan credit bureau")
(def jcb-icon "jcb")
(def joomla-icon "joomla")
(def jpy-icon "jpy")
(def jsfiddle-icon "jsfiddle")
(def key-icon "key")

(def keyboard-icon "keyboard")
(def krw-icon "krw")
(def lab-icon "lab")
(def laptop-icon "laptop")
(def lastfm-square-icon "lastfm square")
(def lastfm-icon "lastfm")
(def law-icon "law")

(def leaf-icon "leaf")
(def leanpub-icon "leanpub")
(def left-dropdown-icon "left dropdown")
(def legal-icon "legal")
(def lemon-icon "lemon")
(def lesbian-icon "lesbian")
(def level-down-icon "level down")

(def level-up-icon "level up")
(def life-ring-icon "life ring")
(def lightbulb-icon "lightbulb")
(def lightning-icon "lightning")
(def like-outline-icon "like outline")
(def like-icon "like")
(def line-chart-icon "line chart")

(def line-graph-icon "line graph")
(def linkedin-square-icon "linkedin square")
(def linkedin-icon "linkedin")
(def linkify-icon "linkify")
(def linode-icon "linode")
(def linux-icon "linux")
(def lira-icon "lira")

(def list-layout-icon "list layout")
(def list-ol-icon "list ol")
(def list-ul-icon "list ul")
(def list-icon "list")
(def location-arrow-icon "location arrow")
(def lock-icon "lock")
(def log-out-icon "log out")

(def long-arrow-down-icon "long arrow down")
(def long-arrow-left-icon "long arrow left")
(def long-arrow-right-icon "long arrow right")
(def long-arrow-up-icon "long arrow up")
(def low-vision-icon "low vision")
(def magic-icon "magic")
(def magnet-icon "magnet")

(def magnify-icon "magnify")
(def mail-forward-icon "mail forward")
(def mail-outline-icon "mail outline")
(def mail-square-icon "mail square")
(def mail-icon "mail")
(def male-homosexual-icon "male homosexual")
(def male-icon "male")

(def man-icon "man")
(def map-outline-icon "map outline")
(def map-pin-icon "map pin")
(def map-signs-icon "map signs")
(def map-icon "map")
(def marker-icon "marker")
(def mars-alternate-icon "mars alternate")

(def mars-double-icon "mars double")
(def mars-horizontal-icon "mars horizontal")
(def mars-stroke-horizontal-icon "mars stroke horizontal")
(def mars-stroke-vertical-icon "mars stroke vertical")
(def mars-stroke-icon "mars stroke")
(def mars-vertical-icon "mars vertical")
(def mars-icon "mars")

(def mastercard-card-icon "mastercard card")
(def mastercard-icon "mastercard")
(def maxcdn-icon "maxcdn")
(def maximize-icon "maximize")
(def meanpath-icon "meanpath")
(def medium-icon "medium")
(def medkit-icon "medkit")

(def meetup-icon "meetup")
(def meh-icon "meh")
(def mercury-icon "mercury")
(def microchip-icon "microchip")
(def microphone-slash-icon "microphone slash")
(def microphone-icon "microphone")
(def microsoft-edge-icon "microsoft edge")

(def military-icon "military")
(def minimize-icon "minimize")
(def minus-circle-icon "minus circle")
(def minus-square-outline-icon "minus square outline")
(def minus-square-icon "minus square")
(def minus-icon "minus")
(def mixcloud-icon "mixcloud")

(def mobile-icon "mobile")
(def modx-icon "modx")
(def money-icon "money")
(def moon-icon "moon")
(def motorcycle-icon "motorcycle")
(def mouse-pointer-icon "mouse pointer")
(def move-icon "move")

(def ms-edge-icon "ms edge")
(def music-icon "music")
(def mute-icon "mute")
(def neuter-icon "neuter")
(def new-pied-piper-icon "new pied piper")
(def newspaper-icon "newspaper")
(def non-binary-transgender-icon "non binary transgender")

(def numbered-list-icon "numbered list")
(def object-group-icon "object group")
(def object-ungroup-icon "object ungroup")
(def odnoklassniki-square-icon "odnoklassniki square")
(def odnoklassniki-icon "odnoklassniki")
(def opencart-icon "opencart")
(def openid-icon "openid")

(def opera-icon "opera")
(def optinmonster-icon "optinmonster")
(def options-icon "options")
(def ordered-list-icon "ordered list")
(def other-gender-horizontal-icon "other gender horizontal")
(def other-gender-vertical-icon "other gender vertical")
(def other-gender-icon "other gender")

(def outdent-icon "outdent")
(def pagelines-icon "pagelines")
(def paint-brush-icon "paint brush")
(def paragraph-icon "paragraph")
(def paste-icon "paste")
(def pause-circle-outline-icon "pause circle outline")
(def pause-circle-icon "pause circle")

(def pause-icon "pause")
(def paw-icon "paw")
(def payment-icon "payment")
(def paypal-card-icon "paypal card")
(def paypal-icon "paypal")
(def pencil-square-icon "pencil square")
(def pencil-icon "pencil")

(def percent-icon "percent")
(def phone-square-icon "phone square")
(def phone-icon "phone")
(def photo-icon "photo")
(def picture-icon "picture")
(def pie-chart-icon "pie chart")
(def pie-graph-icon "pie graph")

(def pied-piper-alternate-icon "pied piper alternate")
(def pied-piper-hat-icon "pied piper hat")
(def pied-piper-icon "pied piper")
(def pin-icon "pin")
(def pinterest-square-icon "pinterest square")
(def pinterest-icon "pinterest")
(def plane-icon "plane")

(def play-circle-outline-icon "play circle outline")
(def play-circle-icon "play circle")
(def play-icon "play")
(def plug-icon "plug")
(def plus-cart-icon "plus cart")
(def plus-circle-icon "plus circle")
(def plus-square-outline-icon "plus square outline")

(def plus-square-icon "plus square")
(def plus-icon "plus")
(def pocket-icon "pocket")
(def podcast-icon "podcast")
(def point-icon "point")
(def pointing-down-icon "pointing down")
(def pointing-left-icon "pointing left")

(def pointing-right-icon "pointing right")
(def pointing-up-icon "pointing up")
(def pound-icon "pound")
(def power-cord-icon "power cord")
(def power-icon "power")
(def print-icon "print")
(def privacy-icon "privacy")

(def product-hunt-icon "product hunt")
(def protect-icon "protect")
(def puzzle-icon "puzzle")
(def qq-icon "qq")
(def qrcode-icon "qrcode")
(def question-circle-outline-icon "question circle outline")
(def question-circle-icon "question circle")

(def question-icon "question")
(def quora-icon "quora")
(def quote-left-icon "quote left")
(def quote-right-icon "quote right")
(def r-circle-icon "r circle")
(def radio-icon "radio")
(def rain-icon "rain")

(def random-icon "random")
(def ravelry-icon "ravelry")
(def rebel-icon "rebel")
(def record-icon "record")
(def recycle-icon "recycle")
(def reddit-alien-icon "reddit alien")
(def reddit-square-icon "reddit square")

(def reddit-icon "reddit")
(def refresh-icon "refresh")
(def registered-icon "registered")
(def remove-bookmark-icon "remove bookmark")
(def remove-circle-outline-icon "remove circle outline")
(def remove-circle-icon "remove circle")
(def remove-from-calendar-icon "remove from calendar")

(def remove-user-icon "remove user")
(def remove-icon "remove")
(def renren-icon "renren")
(def repeat-icon "repeat")
(def reply-all-icon "reply all")
(def reply-icon "reply")
(def resize-horizontal-icon "resize horizontal")

(def resize-vertical-icon "resize vertical")
(def retweet-icon "retweet")
(def rmb-icon "rmb")
(def road-icon "road")
(def rocket-icon "rocket")
(def rouble-icon "rouble")
(def rss-square-icon "rss square")

(def rss-icon "rss")
(def rub-icon "rub")
(def ruble-icon "ruble")
(def rupee-icon "rupee")
(def s15-icon "s15")
(def safari-icon "safari")
(def save-icon "save")

(def scribd-icon "scribd")
(def search-icon "search")
(def selected-radio-icon "selected radio")
(def sellsy-icon "sellsy")
(def send-outline-icon "send outline")
(def send-icon "send")
(def server-icon "server")

(def setting-icon "setting")
(def settings-icon "settings")
(def share-alternate-square-icon "share alternate square")
(def share-alternate-icon "share alternate")
(def share-square-icon "share square")
(def share-icon "share")
(def shekel-icon "shekel")

(def sheqel-icon "sheqel")
(def shield-icon "shield")
(def ship-icon "ship")
(def shipping-icon "shipping")
(def shirtsinbulk-icon "shirtsinbulk")
(def shop-icon "shop")
(def shopping-bag-icon "shopping bag")

(def shopping-basket-icon "shopping basket")
(def shopping-cart-icon "shopping cart")
(def shuffle-icon "shuffle")
(def shutdown-icon "shutdown")
(def sidebar-icon "sidebar")
(def sign-in-icon "sign in")
(def sign-language-icon "sign language")

(def sign-out-icon "sign out")
(def signal-icon "signal")
(def signing-icon "signing")
(def signup-icon "signup")
(def simplybuilt-icon "simplybuilt")
(def sitemap-icon "sitemap")
(def skyatlas-icon "skyatlas")

(def skype-icon "skype")
(def slack-icon "slack")
(def sliders-icon "sliders")
(def slideshare-icon "slideshare")
(def smile-icon "smile")
(def snapchat-ghost-icon "snapchat ghost")
(def snapchat-square-icon "snapchat square")

(def snapchat-icon "snapchat")
(def snowflake-outline-icon "snowflake outline")
(def soccer-icon "soccer")
(def sort-alphabet-ascending-icon "sort alphabet ascending")
(def sort-alphabet-descending-icon "sort alphabet descending")
(def sort-ascending-icon "sort ascending")
(def sort-content-ascending-icon "sort content ascending")

(def sort-content-descending-icon "sort content descending")
(def sort-descending-icon "sort descending")
(def sort-numeric-ascending-icon "sort numeric ascending")
(def sort-numeric-descending-icon "sort numeric descending")
(def sort-icon "sort")
(def sound-icon "sound")
(def soundcloud-icon "soundcloud")

(def space-shuttle-icon "space shuttle")
(def spinner-icon "spinner")
(def spoon-icon "spoon")
(def spotify-icon "spotify")
(def spy-icon "spy")
(def square-outline-icon "square outline")
(def square-icon "square")

(def stack-exchange-icon "stack exchange")
(def stack-overflow-icon "stack overflow")
(def star-half-empty-icon "star half empty")
(def star-half-full-icon "star half full")
(def star-half-icon "star half")
(def star-icon "star")
(def steam-square-icon "steam square")

(def steam-icon "steam")
(def step-backward-icon "step backward")
(def step-forward-icon "step forward")
(def sticky-note-outline-icon "sticky note outline")
(def sticky-note-icon "sticky note")
(def stop-circle-outline-icon "stop circle outline")
(def stop-circle-icon "stop circle")

(def stop-icon "stop")
(def street-view-icon "street view")
(def strikethrough-icon "strikethrough")
(def stripe-card-icon "stripe card")
(def stripe-icon "stripe")
(def student-icon "student")
(def stumbleupon-circle-icon "stumbleupon circle")

(def stumbleupon-icon "stumbleupon")
(def subscript-icon "subscript")
(def subway-icon "subway")
(def suitcase-icon "suitcase")
(def sun-icon "sun")
(def superpowers-icon "superpowers")
(def superscript-icon "superscript")

(def table-icon "table")
(def tablet-icon "tablet")
(def tag-icon "tag")
(def tags-icon "tags")
(def talk-outline-icon "talk outline")
(def talk-icon "talk")
(def target-icon "target")

(def tasks-icon "tasks")
(def taxi-icon "taxi")
(def telegram-icon "telegram")
(def teletype-icon "teletype")
(def television-icon "television")
(def tencent-weibo-icon "tencent weibo")
(def terminal-icon "terminal")

(def text-cursor-icon "text cursor")
(def text-height-icon "text height")
(def text-telephone-icon "text telephone")
(def text-width-icon "text width")
(def theme-isle-icon "theme isle")
(def theme-icon "theme")
(def themeisle-icon "themeisle")

(def thermometer-empty-icon "thermometer empty")
(def thermometer-full-icon "thermometer full")
(def thermometer-half-icon "thermometer half")
(def thermometer-quarter-icon "thermometer quarter")
(def thermometer-three-quarters-icon "thermometer three quarters")
(def thermometer-icon "thermometer")
(def thumb-tack-icon "thumb tack")

(def thumbs-down-icon "thumbs down")
(def thumbs-outline-down-icon "thumbs outline down")
(def thumbs-outline-up-icon "thumbs outline up")
(def thumbs-up-icon "thumbs up")
(def ticket-icon "ticket")
(def time-icon "time")
(def times-rectangle-outline-icon "times rectangle outline")

(def times-rectangle-icon "times rectangle")
(def tint-icon "tint")
(def tm-icon "tm")
(def toggle-down-icon "toggle down")
(def toggle-left-icon "toggle left")
(def toggle-off-icon "toggle off")
(def toggle-on-icon "toggle on")

(def toggle-right-icon "toggle right")
(def toggle-up-icon "toggle up")
(def trademark-icon "trademark")
(def train-icon "train")
(def transgender-icon "transgender")
(def translate-icon "translate")
(def trash-outline-icon "trash outline")

(def trash-icon "trash")
(def travel-icon "travel")
(def treatment-icon "treatment")
(def tree-icon "tree")
(def trello-icon "trello")
(def triangle-down-icon "triangle down")
(def triangle-left-icon "triangle left")

(def triangle-right-icon "triangle right")
(def triangle-up-icon "triangle up")
(def tripadvisor-icon "tripadvisor")
(def trophy-icon "trophy")
(def truck-icon "truck")
(def try-icon "try")
(def tty-icon "tty")

(def tumblr-square-icon "tumblr square")
(def tumblr-icon "tumblr")
(def tv-icon "tv")
(def twitch-icon "twitch")
(def twitter-square-icon "twitter square")
(def twitter-icon "twitter")
(def umbrella-icon "umbrella")

(def underline-icon "underline")
(def undo-icon "undo")
(def unhide-icon "unhide")
(def universal-access-icon "universal access")
(def university-icon "university")
(def unlinkify-icon "unlinkify")
(def unlock-alternate-icon "unlock alternate")

(def unlock-icon "unlock")
(def unmute-icon "unmute")
(def unordered-list-icon "unordered list")
(def upload-icon "upload")
(def usb-icon "usb")
(def usd-icon "usd")
(def user-cancel-icon "user cancel")

(def user-circle-outline-icon "user circle outline")
(def user-circle-icon "user circle")
(def user-close-icon "user close")
(def user-delete-icon "user delete")
(def user-outline-icon "user outline")
(def user-plus-icon "user plus")
(def user-times-icon "user times")

(def user-x-icon "user x")
(def user-icon "user")
(def users-icon "users")
(def vcard-outline-icon "vcard outline")
(def vcard-icon "vcard")
(def venus-double-icon "venus double")
(def venus-mars-icon "venus mars")

(def venus-icon "venus")
(def viacoin-icon "viacoin")
(def viadeo-square-icon "viadeo square")
(def viadeo-icon "viadeo")
(def video-camera-icon "video camera")
(def video-play-outline-icon "video play outline")
(def video-play-icon "video play")

(def video-icon "video")
(def vimeo-square-icon "vimeo square")
(def vimeo-icon "vimeo")
(def vine-icon "vine")
(def visa-card-icon "visa card")
(def visa-icon "visa")
(def vk-icon "vk")

(def volume-control-phone-icon "volume control phone")
(def volume-down-icon "volume down")
(def volume-off-icon "volume off")
(def volume-up-icon "volume up")
(def wait-icon "wait")
(def warning-circle-icon "warning circle")
(def warning-sign-icon "warning sign")

(def warning-icon "warning")
(def wechat-icon "wechat")
(def weibo-icon "weibo")
(def weixin-icon "weixin")
(def whatsapp-icon "whatsapp")
(def wheelchair-icon "wheelchair")
(def wifi-icon "wifi")

(def wikipedia-icon "wikipedia")
(def window-close-outline-icon "window close outline")
(def window-close-icon "window close")
(def window-maximize-icon "window maximize")
(def window-minimize-icon "window minimize")
(def window-restore-icon "window restore")
(def windows-icon "windows")

(def winner-icon "winner")
(def wizard-icon "wizard")
(def woman-icon "woman")
(def won-icon "won")
(def wordpress-beginner-icon "wordpress beginner")
(def wordpress-forms-icon "wordpress forms")
(def wordpress-icon "wordpress")

(def world-icon "world")
(def wpbeginner-icon "wpbeginner")
(def wpexplorer-icon "wpexplorer")
(def wpforms-icon "wpforms")
(def wrench-icon "wrench")
(def write-square-icon "write square")
(def write-icon "write")

(def x-icon "x")
(def xing-square-icon "xing square")
(def xing-icon "xing")
(def y-combinator-icon "y combinator")
(def yahoo-icon "yahoo")
(def yc-icon "yc")
(def ycombinator-icon "ycombinator")

(def yelp-icon "yelp")
(def yen-icon "yen")
(def yoast-icon "yoast")
(def youtube-play-icon "youtube play")
(def youtube-square-icon "youtube square")
(def youtube-icon "youtube")
(def zip-icon "zip")

(def zoom-in-icon "zoom in")
(def zoom-out-icon "zoom out")
(def zoom-icon "zoom")

