(ns fulcrologic.semantic-ui.icons)

(def add-circle "add circle")
(def add-square "add square")
(def add-to-calendar "add to calendar")
(def add-to-cart "add to cart")
(def add-user "add user")
(def add "add")
(def address-book-outline "address book outline")
(def address-book "address book")
(def address-card-outline "address card outline")
(def address-card "address card")
(def adjust "adjust")
(def adn "adn")

(def alarm-mute-outline "alarm mute outline")
(def alarm-mute "alarm mute")
(def alarm-outline "alarm outline")
(def alarm "alarm")
(def ald "ald")
(def align-center "align center")
(def align-justify "align justify")

(def align-left "align left")
(def align-right "align right")
(def als "als")
(def amazon "amazon")
(def ambulance "ambulance")
(def american-express-card "american express card")
(def american-express "american express")

(def american-sign-language-interpreting "american sign language interpreting")
(def amex "amex")
(def anchor "anchor")
(def android "android")
(def angellist "angellist")
(def angle-double-down "angle double down")
(def angle-double-left "angle double left")

(def angle-double-right "angle double right")
(def angle-double-up "angle double up")
(def angle-down "angle down")
(def angle-left "angle left")
(def angle-right "angle right")
(def angle-up "angle up")
(def announcement "announcement")

(def apple "apple")
(def archive "archive")
(def area-chart "area chart")
(def area-graph "area graph")
(def arrow-circle-down "arrow circle down")
(def arrow-circle-left "arrow circle left")
(def arrow-circle-outline-down "arrow circle outline down")

(def arrow-circle-outline-left "arrow circle outline left")
(def arrow-circle-outline-right "arrow circle outline right")
(def arrow-circle-outline-up "arrow circle outline up")
(def arrow-circle-right "arrow circle right")
(def arrow-circle-up "arrow circle up")
(def arrow-down-cart "arrow down cart")
(def arrow-down "arrow down")

(def arrow-left "arrow left")
(def arrow-right "arrow right")
(def arrow-up "arrow up")
(def asexual "asexual")
(def asl-interpreting "asl interpreting")
(def asl "asl")
(def assistive-listening-devices "assistive listening devices")

(def assistive-listening-systems "assistive listening systems")
(def asterisk "asterisk")
(def at "at")
(def attach "attach")
(def attention "attention")
(def audio-description "audio description")
(def backward "backward")

(def balance "balance")
(def ban "ban")
(def bandcamp "bandcamp")
(def bar-chart "bar chart")
(def bar-graph "bar graph")
(def bar "bar")
(def barcode "barcode")

(def bars "bars")
(def bath "bath")
(def bathtub "bathtub")
(def battery-empty "battery empty")
(def battery-four "battery four")
(def battery-full "battery full")
(def battery-half "battery half")

(def battery-high "battery high")
(def battery-low "battery low")
(def battery-medium "battery medium")
(def battery-one "battery one")
(def battery-quarter "battery quarter")
(def battery-three-quarters "battery three quarters")
(def battery-three "battery three")

(def battery-two "battery two")
(def battery-zero "battery zero")
(def bed "bed")
(def beer "beer")
(def behance-square "behance square")
(def behance "behance")
(def bell-outline "bell outline")

(def bell-slash-outline "bell slash outline")
(def bell-slash "bell slash")
(def bell "bell")
(def bicycle "bicycle")
(def binoculars "binoculars")
(def birthday "birthday")
(def bitbucket-square "bitbucket square")

(def bitbucket "bitbucket")
(def bitcoin "bitcoin")
(def black-tie "black tie")
(def blind "blind")
(def block-layout "block layout")
(def bluetooth-alternative "bluetooth alternative")
(def bluetooth "bluetooth")

(def bold "bold")
(def bomb "bomb")
(def book "book")
(def bookmark-outline "bookmark outline")
(def bookmark "bookmark")
(def braille "braille")
(def briefcase "briefcase")

(def broken-chain "broken chain")
(def browser "browser")
(def btc "btc")
(def bug "bug")
(def building-outline "building outline")
(def building "building")
(def bullhorn "bullhorn")

(def bullseye "bullseye")
(def bus "bus")
(def buysellads "buysellads")
(def calculator "calculator")
(def calendar-check "calendar check")
(def calendar-minus "calendar minus")
(def calendar-outline "calendar outline")

(def calendar-plus "calendar plus")
(def calendar-times "calendar times")
(def calendar "calendar")
(def call-square "call square")
(def call "call")
(def camera-retro "camera retro")
(def camera "camera")

(def cancel "cancel")
(def car "car")
(def caret-down "caret down")
(def caret-left "caret left")
(def caret-right "caret right")
(def caret-up "caret up")
(def cart "cart")

(def cc "cc")
(def certificate "certificate")
(def chain "chain")
(def chat "chat")
(def check-circle-outline "check circle outline")
(def check-circle "check circle")
(def check-square "check square")

(def check "check")
(def checked-calendar "checked calendar")
(def checkmark-box "checkmark box")
(def checkmark "checkmark")
(def chevron-circle-down "chevron circle down")
(def chevron-circle-left "chevron circle left")
(def chevron-circle-right "chevron circle right")

(def chevron-circle-up "chevron circle up")
(def chevron-down "chevron down")
(def chevron-left "chevron left")
(def chevron-right "chevron right")
(def chevron-up "chevron up")
(def child "child")
(def chrome "chrome")

(def circle-notched "circle notched")
(def circle-outline "circle outline")
(def circle-thin "circle thin")
(def circle "circle")
(def clipboard "clipboard")
(def clock "clock")
(def clone "clone")

(def close "close")
(def closed-captioning "closed captioning")
(def cloud-download "cloud download")
(def cloud-upload "cloud upload")
(def cloud "cloud")
(def cny "cny")
(def cocktail "cocktail")

(def code "code")
(def codepen "codepen")
(def codiepie "codiepie")
(def coffee "coffee")
(def cogs "cogs")
(def columns "columns")
(def comment-outline "comment outline")

(def comment "comment")
(def commenting-outline "commenting outline")
(def commenting "commenting")
(def comments-outline "comments outline")
(def comments "comments")
(def compass "compass")
(def compose "compose")

(def compress "compress")
(def computer "computer")
(def configure "configure")
(def connectdevelop "connectdevelop")
(def contao "contao")
(def content "content")
(def conversation "conversation")

(def copy "copy")
(def copyright "copyright")
(def creative-commons "creative commons")
(def credit-card-alternative "credit card alternative")
(def credit-card "credit card")
(def crop "crop")
(def crosshairs "crosshairs")

(def css3 "css3")
(def cube "cube")
(def cubes "cubes")
(def currency "currency")
(def cut "cut")
(def dashboard "dashboard")
(def dashcube "dashcube")

(def database "database")
(def deaf "deaf")
(def deafness "deafness")
(def delete-calendar "delete calendar")
(def delete "delete")
(def delicious "delicious")
(def desktop "desktop")

(def detective "detective")
(def deviantart "deviantart")
(def diamond "diamond")
(def digg "digg")
(def diners-club-card "diners club card")
(def diners-club "diners club")
(def discover-card "discover card")

(def discover "discover")
(def discussions "discussions")
(def disk-outline "disk outline")
(def dislike-outline "dislike outline")
(def doctor "doctor")
(def dollar "dollar")
(def dont "dont")

(def dot-circle-outline "dot circle outline")
(def download "download")
(def dribble "dribble")
(def drivers-license-outline "drivers license outline")
(def drivers-license "drivers license")
(def dropbox "dropbox")
(def dropdown "dropdown")

(def drupal "drupal")
(def edge "edge")
(def edit "edit")
(def eercast "eercast")
(def eject "eject")
(def ellipsis-horizontal "ellipsis horizontal")
(def ellipsis-vertical "ellipsis vertical")

(def emergency "emergency")
(def empire "empire")
(def empty-heart "empty heart")
(def empty-star "empty star")
(def envelope "envelope")
(def envira-gallery "envira gallery")
(def envira "envira")

(def erase "erase")
(def eraser "eraser")
(def etsy "etsy")
(def eur "eur")
(def euro "euro")
(def exchange "exchange")
(def exclamation-circle "exclamation circle")

(def exclamation-triangle "exclamation triangle")
(def exclamation "exclamation")
(def expand "expand")
(def expeditedssl "expeditedssl")
(def external-share "external share")
(def external-square "external square")
(def external "external")

(def eye "eye")
(def eyedropper "eyedropper")
(def fa "fa")
(def facebook-f "facebook f")
(def facebook-official "facebook official")
(def facebook-square "facebook square")
(def facebook "facebook")

(def factory "factory")
(def fast-backward "fast backward")
(def fast-forward "fast forward")
(def favorite "favorite")
(def fax "fax")
(def feed "feed")
(def female-homosexual "female homosexual")

(def female "female")
(def fighter-jet "fighter jet")
(def file-archive-outline "file archive outline")
(def file-audio-outline "file audio outline")
(def file-code-outline "file code outline")
(def file-excel-outline "file excel outline")
(def file-image-outline "file image outline")

(def file-outline "file outline")
(def file-pdf-outline "file pdf outline")
(def file-powerpoint-outline "file powerpoint outline")
(def file-text-outline "file text outline")
(def file-text "file text")
(def file-video-outline "file video outline")
(def file-word-outline "file word outline")

(def file "file")
(def film "film")
(def filter "filter")
(def find "find")
(def fire-extinguisher "fire extinguisher")
(def fire "fire")
(def firefox "firefox")

(def first-aid "first aid")
(def first-order "first order")
(def five-hundred-pixels "five hundred pixels")
(def flag-checkered "flag checkered")
(def flag-outline "flag outline")
(def flag "flag")
(def flask "flask")

(def flickr "flickr")
(def folder-open-outline "folder open outline")
(def folder-open "folder open")
(def folder-outline "folder outline")
(def folder "folder")
(def font-awesome "font awesome")
(def font "font")

(def fonticons "fonticons")
(def food "food")
(def fork "fork")
(def fort-awesome "fort awesome")
(def forumbee "forumbee")
(def forward "forward")
(def foursquare "foursquare")

(def free-code-camp "free code camp")
(def frown "frown")
(def game "game")
(def gamepad "gamepad")
(def gay "gay")
(def gbp "gbp")
(def genderless "genderless")

(def gg-circle "gg circle")
(def gg "gg")
(def gift "gift")
(def git-square "git square")
(def git "git")
(def github-alternate "github alternate")
(def github-square "github square")

(def github "github")
(def gitlab "gitlab")
(def gittip "gittip")
(def glide-g "glide g")
(def glide "glide")
(def globe "globe")
(def google-plus-circle "google plus circle")

(def google-plus-official "google plus official")
(def google-plus-square "google plus square")
(def google-plus "google plus")
(def google-wallet "google wallet")
(def google "google")
(def grab "grab")
(def graduation "graduation")

(def gratipay "gratipay")
(def grav "grav")
(def grid-layout "grid layout")
(def group "group")
(def h "h")
(def hacker-news "hacker news")
(def hand-lizard "hand lizard")

(def hand-outline-down "hand outline down")
(def hand-outline-left "hand outline left")
(def hand-outline-right "hand outline right")
(def hand-outline-up "hand outline up")
(def hand-paper "hand paper")
(def hand-peace "hand peace")
(def hand-pointer "hand pointer")

(def hand-rock "hand rock")
(def hand-scissors "hand scissors")
(def hand-spock "hand spock")
(def hand-victory "hand victory")
(def handicap "handicap")
(def hard-of-hearing "hard of hearing")
(def hashtag "hashtag")

(def hdd-outline "hdd outline")
(def header "header")
(def headphone "headphone")
(def heart-outline "heart outline")
(def heart "heart")
(def heartbeat "heartbeat")
(def help-circle-outline "help circle outline")

(def help-circle "help circle")
(def help "help")
(def heterosexual "heterosexual")
(def hide "hide")
(def history "history")
(def home "home")
(def hospital "hospital")

(def hotel "hotel")
(def hourglass-empty "hourglass empty")
(def hourglass-end "hourglass end")
(def hourglass-four "hourglass four")
(def hourglass-full "hourglass full")
(def hourglass-half "hourglass half")
(def hourglass-one "hourglass one")

(def hourglass-outline "hourglass outline")
(def hourglass-start "hourglass start")
(def hourglass-three "hourglass three")
(def hourglass-two "hourglass two")
(def hourglass-zero "hourglass zero")
(def houzz "houzz")
(def html5 "html5")

(def i-cursor "i cursor")
(def id-badge "id badge")
(def id-card-outline "id card outline")
(def id-card "id card")
(def idea "idea")
(def ils "ils")
(def image "image")

(def imdb "imdb")
(def in-cart "in cart")
(def inbox "inbox")
(def indent "indent")
(def industry "industry")
(def info-circle "info circle")
(def info "info")

(def inr "inr")
(def instagram "instagram")
(def intergender "intergender")
(def internet-explorer "internet explorer")
(def intersex "intersex")
(def ioxhost "ioxhost")
(def italic "italic")

(def japan-credit-bureau-card "japan credit bureau card")
(def japan-credit-bureau "japan credit bureau")
(def jcb "jcb")
(def joomla "joomla")
(def jpy "jpy")
(def jsfiddle "jsfiddle")
(def key "key")

(def keyboard "keyboard")
(def krw "krw")
(def lab "lab")
(def laptop "laptop")
(def lastfm-square "lastfm square")
(def lastfm "lastfm")
(def law "law")

(def leaf "leaf")
(def leanpub "leanpub")
(def left-dropdown "left dropdown")
(def legal "legal")
(def lemon "lemon")
(def lesbian "lesbian")
(def level-down "level down")

(def level-up "level up")
(def life-ring "life ring")
(def lightbulb "lightbulb")
(def lightning "lightning")
(def like-outline "like outline")
(def like "like")
(def line-chart "line chart")

(def line-graph "line graph")
(def linkedin-square "linkedin square")
(def linkedin "linkedin")
(def linkify "linkify")
(def linode "linode")
(def linux "linux")
(def lira "lira")

(def list-layout "list layout")
(def list-ol "list ol")
(def list-ul "list ul")
(def list "list")
(def location-arrow "location arrow")
(def lock "lock")
(def log-out "log out")

(def long-arrow-down "long arrow down")
(def long-arrow-left "long arrow left")
(def long-arrow-right "long arrow right")
(def long-arrow-up "long arrow up")
(def low-vision "low vision")
(def magic "magic")
(def magnet "magnet")

(def magnify "magnify")
(def mail-forward "mail forward")
(def mail-outline "mail outline")
(def mail-square "mail square")
(def mail "mail")
(def male-homosexual "male homosexual")
(def male "male")

(def man "man")
(def map-outline "map outline")
(def map-pin "map pin")
(def map-signs "map signs")
(def map "map")
(def marker "marker")
(def mars-alternate "mars alternate")

(def mars-double "mars double")
(def mars-horizontal "mars horizontal")
(def mars-stroke-horizontal "mars stroke horizontal")
(def mars-stroke-vertical "mars stroke vertical")
(def mars-stroke "mars stroke")
(def mars-vertical "mars vertical")
(def mars "mars")

(def mastercard-card "mastercard card")
(def mastercard "mastercard")
(def maxcdn "maxcdn")
(def maximize "maximize")
(def meanpath "meanpath")
(def medium "medium")
(def medkit "medkit")

(def meetup "meetup")
(def meh "meh")
(def mercury "mercury")
(def microchip "microchip")
(def microphone-slash "microphone slash")
(def microphone "microphone")
(def microsoft-edge "microsoft edge")

(def military "military")
(def minimize "minimize")
(def minus-circle "minus circle")
(def minus-square-outline "minus square outline")
(def minus-square "minus square")
(def minus "minus")
(def mixcloud "mixcloud")

(def mobile "mobile")
(def modx "modx")
(def money "money")
(def moon "moon")
(def motorcycle "motorcycle")
(def mouse-pointer "mouse pointer")
(def move "move")

(def ms-edge "ms edge")
(def music "music")
(def mute "mute")
(def neuter "neuter")
(def new-pied-piper "new pied piper")
(def newspaper "newspaper")
(def non-binary-transgender "non binary transgender")

(def numbered-list "numbered list")
(def object-group "object group")
(def object-ungroup "object ungroup")
(def odnoklassniki-square "odnoklassniki square")
(def odnoklassniki "odnoklassniki")
(def opencart "opencart")
(def openid "openid")

(def opera "opera")
(def optinmonster "optinmonster")
(def options "options")
(def ordered-list "ordered list")
(def other-gender-horizontal "other gender horizontal")
(def other-gender-vertical "other gender vertical")
(def other-gender "other gender")

(def outdent "outdent")
(def pagelines "pagelines")
(def paint-brush "paint brush")
(def paragraph "paragraph")
(def paste "paste")
(def pause-circle-outline "pause circle outline")
(def pause-circle "pause circle")

(def pause "pause")
(def paw "paw")
(def payment "payment")
(def paypal-card "paypal card")
(def paypal "paypal")
(def pencil-square "pencil square")
(def pencil "pencil")

(def percent "percent")
(def phone-square "phone square")
(def phone "phone")
(def photo "photo")
(def picture "picture")
(def pie-chart "pie chart")
(def pie-graph "pie graph")

(def pied-piper-alternate "pied piper alternate")
(def pied-piper-hat "pied piper hat")
(def pied-piper "pied piper")
(def pin "pin")
(def pinterest-square "pinterest square")
(def pinterest "pinterest")
(def plane "plane")

(def play-circle-outline "play circle outline")
(def play-circle "play circle")
(def play "play")
(def plug "plug")
(def plus-cart "plus cart")
(def plus-circle "plus circle")
(def plus-square-outline "plus square outline")

(def plus-square "plus square")
(def plus "plus")
(def pocket "pocket")
(def podcast "podcast")
(def point "point")
(def pointing-down "pointing down")
(def pointing-left "pointing left")

(def pointing-right "pointing right")
(def pointing-up "pointing up")
(def pound "pound")
(def power-cord "power cord")
(def power "power")
(def print "print")
(def privacy "privacy")

(def product-hunt "product hunt")
(def protect "protect")
(def puzzle "puzzle")
(def qq "qq")
(def qrcode "qrcode")
(def question-circle-outline "question circle outline")
(def question-circle "question circle")

(def question "question")
(def quora "quora")
(def quote-left "quote left")
(def quote-right "quote right")
(def r-circle "r circle")
(def radio "radio")
(def rain "rain")

(def random "random")
(def ravelry "ravelry")
(def rebel "rebel")
(def record "record")
(def recycle "recycle")
(def reddit-alien "reddit alien")
(def reddit-square "reddit square")

(def reddit "reddit")
(def refresh "refresh")
(def registered "registered")
(def remove-bookmark "remove bookmark")
(def remove-circle-outline "remove circle outline")
(def remove-circle "remove circle")
(def remove-from-calendar "remove from calendar")

(def remove-user "remove user")
(def remove "remove")
(def renren "renren")
(def repeat "repeat")
(def reply-all "reply all")
(def reply "reply")
(def resize-horizontal "resize horizontal")

(def resize-vertical "resize vertical")
(def retweet "retweet")
(def rmb "rmb")
(def road "road")
(def rocket "rocket")
(def rouble "rouble")
(def rss-square "rss square")

(def rss "rss")
(def rub "rub")
(def ruble "ruble")
(def rupee "rupee")
(def s15 "s15")
(def safari "safari")
(def save "save")

(def scribd "scribd")
(def search "search")
(def selected-radio "selected radio")
(def sellsy "sellsy")
(def send-outline "send outline")
(def send "send")
(def server "server")

(def setting "setting")
(def settings "settings")
(def share-alternate-square "share alternate square")
(def share-alternate "share alternate")
(def share-square "share square")
(def share "share")
(def shekel "shekel")

(def sheqel "sheqel")
(def shield "shield")
(def ship "ship")
(def shipping "shipping")
(def shirtsinbulk "shirtsinbulk")
(def shop "shop")
(def shopping-bag "shopping bag")

(def shopping-basket "shopping basket")
(def shopping-cart "shopping cart")
(def shuffle "shuffle")
(def shutdown "shutdown")
(def sidebar "sidebar")
(def sign-in "sign in")
(def sign-language "sign language")

(def sign-out "sign out")
(def signal "signal")
(def signing "signing")
(def signup "signup")
(def simplybuilt "simplybuilt")
(def sitemap "sitemap")
(def skyatlas "skyatlas")

(def skype "skype")
(def slack "slack")
(def sliders "sliders")
(def slideshare "slideshare")
(def smile "smile")
(def snapchat-ghost "snapchat ghost")
(def snapchat-square "snapchat square")

(def snapchat "snapchat")
(def snowflake-outline "snowflake outline")
(def soccer "soccer")
(def sort-alphabet-ascending "sort alphabet ascending")
(def sort-alphabet-descending "sort alphabet descending")
(def sort-ascending "sort ascending")
(def sort-content-ascending "sort content ascending")

(def sort-content-descending "sort content descending")
(def sort-descending "sort descending")
(def sort-numeric-ascending "sort numeric ascending")
(def sort-numeric-descending "sort numeric descending")
(def sort "sort")
(def sound "sound")
(def soundcloud "soundcloud")

(def space-shuttle "space shuttle")
(def spinner "spinner")
(def spoon "spoon")
(def spotify "spotify")
(def spy "spy")
(def square-outline "square outline")
(def square "square")

(def stack-exchange "stack exchange")
(def stack-overflow "stack overflow")
(def star-half-empty "star half empty")
(def star-half-full "star half full")
(def star-half "star half")
(def star "star")
(def steam-square "steam square")

(def steam "steam")
(def step-backward "step backward")
(def step-forward "step forward")
(def sticky-note-outline "sticky note outline")
(def sticky-note "sticky note")
(def stop-circle-outline "stop circle outline")
(def stop-circle "stop circle")

(def stop "stop")
(def street-view "street view")
(def strikethrough "strikethrough")
(def stripe-card "stripe card")
(def stripe "stripe")
(def student "student")
(def stumbleupon-circle "stumbleupon circle")

(def stumbleupon "stumbleupon")
(def subscript "subscript")
(def subway "subway")
(def suitcase "suitcase")
(def sun "sun")
(def superpowers "superpowers")
(def superscript "superscript")

(def table "table")
(def tablet "tablet")
(def tag "tag")
(def tags "tags")
(def talk-outline "talk outline")
(def talk "talk")
(def target "target")

(def tasks "tasks")
(def taxi "taxi")
(def telegram "telegram")
(def teletype "teletype")
(def television "television")
(def tencent-weibo "tencent weibo")
(def terminal "terminal")

(def text-cursor "text cursor")
(def text-height "text height")
(def text-telephone "text telephone")
(def text-width "text width")
(def theme-isle "theme isle")
(def theme "theme")
(def themeisle "themeisle")

(def thermometer-empty "thermometer empty")
(def thermometer-full "thermometer full")
(def thermometer-half "thermometer half")
(def thermometer-quarter "thermometer quarter")
(def thermometer-three-quarters "thermometer three quarters")
(def thermometer "thermometer")
(def thumb-tack "thumb tack")

(def thumbs-down "thumbs down")
(def thumbs-outline-down "thumbs outline down")
(def thumbs-outline-up "thumbs outline up")
(def thumbs-up "thumbs up")
(def ticket "ticket")
(def time "time")
(def times-rectangle-outline "times rectangle outline")

(def times-rectangle "times rectangle")
(def tint "tint")
(def tm "tm")
(def toggle-down "toggle down")
(def toggle-left "toggle left")
(def toggle-off "toggle off")
(def toggle-on "toggle on")

(def toggle-right "toggle right")
(def toggle-up "toggle up")
(def trademark "trademark")
(def train "train")
(def transgender "transgender")
(def translate "translate")
(def trash-outline "trash outline")

(def trash "trash")
(def travel "travel")
(def treatment "treatment")
(def tree "tree")
(def trello "trello")
(def triangle-down "triangle down")
(def triangle-left "triangle left")

(def triangle-right "triangle right")
(def triangle-up "triangle up")
(def tripadvisor "tripadvisor")
(def trophy "trophy")
(def truck "truck")
(def try "try")
(def tty "tty")

(def tumblr-square "tumblr square")
(def tumblr "tumblr")
(def tv "tv")
(def twitch "twitch")
(def twitter-square "twitter square")
(def twitter "twitter")
(def umbrella "umbrella")

(def underline "underline")
(def undo "undo")
(def unhide "unhide")
(def universal-access "universal access")
(def university "university")
(def unlinkify "unlinkify")
(def unlock-alternate "unlock alternate")

(def unlock "unlock")
(def unmute "unmute")
(def unordered-list "unordered list")
(def upload "upload")
(def usb "usb")
(def usd "usd")
(def user-cancel "user cancel")

(def user-circle-outline "user circle outline")
(def user-circle "user circle")
(def user-close "user close")
(def user-delete "user delete")
(def user-outline "user outline")
(def user-plus "user plus")
(def user-times "user times")

(def user-x "user x")
(def user "user")
(def users "users")
(def vcard-outline "vcard outline")
(def vcard "vcard")
(def venus-double "venus double")
(def venus-mars "venus mars")

(def venus "venus")
(def viacoin "viacoin")
(def viadeo-square "viadeo square")
(def viadeo "viadeo")
(def video-camera "video camera")
(def video-play-outline "video play outline")
(def video-play "video play")

(def video "video")
(def vimeo-square "vimeo square")
(def vimeo "vimeo")
(def vine "vine")
(def visa-card "visa card")
(def visa "visa")
(def vk "vk")

(def volume-control-phone "volume control phone")
(def volume-down "volume down")
(def volume-off "volume off")
(def volume-up "volume up")
(def wait "wait")
(def warning-circle "warning circle")
(def warning-sign "warning sign")

(def warning "warning")
(def wechat "wechat")
(def weibo "weibo")
(def weixin "weixin")
(def whatsapp "whatsapp")
(def wheelchair "wheelchair")
(def wifi "wifi")

(def wikipedia "wikipedia")
(def window-close-outline "window close outline")
(def window-close "window close")
(def window-maximize "window maximize")
(def window-minimize "window minimize")
(def window-restore "window restore")
(def windows "windows")

(def winner "winner")
(def wizard "wizard")
(def woman "woman")
(def won "won")
(def wordpress-beginner "wordpress beginner")
(def wordpress-forms "wordpress forms")
(def wordpress "wordpress")

(def world "world")
(def wpbeginner "wpbeginner")
(def wpexplorer "wpexplorer")
(def wpforms "wpforms")
(def wrench "wrench")
(def write-square "write square")
(def write "write")

(def x "x")
(def xing-square "xing square")
(def xing "xing")
(def y-combinator "y combinator")
(def yahoo "yahoo")
(def yc "yc")
(def ycombinator "ycombinator")

(def yelp "yelp")
(def yen "yen")
(def yoast "yoast")
(def youtube-play "youtube play")
(def youtube-square "youtube square")
(def youtube "youtube")
(def zip "zip")

(def zoom-in "zoom in")
(def zoom-out "zoom out")
(def zoom "zoom")

